// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model/dynamicforkjointask.proto

package com.netflix.conductor.proto;

public final class DynamicForkJoinTaskPb {
  private DynamicForkJoinTaskPb() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DynamicForkJoinTaskOrBuilder extends
      // @@protoc_insertion_point(interface_extends:conductor.proto.DynamicForkJoinTask)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string task_name = 1;</code>
     * @return The taskName.
     */
    java.lang.String getTaskName();
    /**
     * <code>string task_name = 1;</code>
     * @return The bytes for taskName.
     */
    com.google.protobuf.ByteString
        getTaskNameBytes();

    /**
     * <code>string workflow_name = 2;</code>
     * @return The workflowName.
     */
    java.lang.String getWorkflowName();
    /**
     * <code>string workflow_name = 2;</code>
     * @return The bytes for workflowName.
     */
    com.google.protobuf.ByteString
        getWorkflowNameBytes();

    /**
     * <code>string reference_name = 3;</code>
     * @return The referenceName.
     */
    java.lang.String getReferenceName();
    /**
     * <code>string reference_name = 3;</code>
     * @return The bytes for referenceName.
     */
    com.google.protobuf.ByteString
        getReferenceNameBytes();

    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; input = 4;</code>
     */
    int getInputCount();
    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; input = 4;</code>
     */
    boolean containsInput(
        java.lang.String key);
    /**
     * Use {@link #getInputMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, com.google.protobuf.Value>
    getInput();
    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; input = 4;</code>
     */
    java.util.Map<java.lang.String, com.google.protobuf.Value>
    getInputMap();
    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; input = 4;</code>
     */

    com.google.protobuf.Value getInputOrDefault(
        java.lang.String key,
        com.google.protobuf.Value defaultValue);
    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; input = 4;</code>
     */

    com.google.protobuf.Value getInputOrThrow(
        java.lang.String key);

    /**
     * <code>string type = 5;</code>
     * @return The type.
     */
    java.lang.String getType();
    /**
     * <code>string type = 5;</code>
     * @return The bytes for type.
     */
    com.google.protobuf.ByteString
        getTypeBytes();
  }
  /**
   * Protobuf type {@code conductor.proto.DynamicForkJoinTask}
   */
  public static final class DynamicForkJoinTask extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:conductor.proto.DynamicForkJoinTask)
      DynamicForkJoinTaskOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DynamicForkJoinTask.newBuilder() to construct.
    private DynamicForkJoinTask(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DynamicForkJoinTask() {
      taskName_ = "";
      workflowName_ = "";
      referenceName_ = "";
      type_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new DynamicForkJoinTask();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DynamicForkJoinTask(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              taskName_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              workflowName_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              referenceName_ = s;
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                input_ = com.google.protobuf.MapField.newMapField(
                    InputDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<java.lang.String, com.google.protobuf.Value>
              input__ = input.readMessage(
                  InputDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              input_.getMutableMap().put(
                  input__.getKey(), input__.getValue());
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              type_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.netflix.conductor.proto.DynamicForkJoinTaskPb.internal_static_conductor_proto_DynamicForkJoinTask_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 4:
          return internalGetInput();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.netflix.conductor.proto.DynamicForkJoinTaskPb.internal_static_conductor_proto_DynamicForkJoinTask_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.netflix.conductor.proto.DynamicForkJoinTaskPb.DynamicForkJoinTask.class, com.netflix.conductor.proto.DynamicForkJoinTaskPb.DynamicForkJoinTask.Builder.class);
    }

    public static final int TASK_NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object taskName_;
    /**
     * <code>string task_name = 1;</code>
     * @return The taskName.
     */
    @java.lang.Override
    public java.lang.String getTaskName() {
      java.lang.Object ref = taskName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        taskName_ = s;
        return s;
      }
    }
    /**
     * <code>string task_name = 1;</code>
     * @return The bytes for taskName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTaskNameBytes() {
      java.lang.Object ref = taskName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        taskName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int WORKFLOW_NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object workflowName_;
    /**
     * <code>string workflow_name = 2;</code>
     * @return The workflowName.
     */
    @java.lang.Override
    public java.lang.String getWorkflowName() {
      java.lang.Object ref = workflowName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        workflowName_ = s;
        return s;
      }
    }
    /**
     * <code>string workflow_name = 2;</code>
     * @return The bytes for workflowName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getWorkflowNameBytes() {
      java.lang.Object ref = workflowName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        workflowName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REFERENCE_NAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object referenceName_;
    /**
     * <code>string reference_name = 3;</code>
     * @return The referenceName.
     */
    @java.lang.Override
    public java.lang.String getReferenceName() {
      java.lang.Object ref = referenceName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        referenceName_ = s;
        return s;
      }
    }
    /**
     * <code>string reference_name = 3;</code>
     * @return The bytes for referenceName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getReferenceNameBytes() {
      java.lang.Object ref = referenceName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        referenceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INPUT_FIELD_NUMBER = 4;
    private static final class InputDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, com.google.protobuf.Value> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, com.google.protobuf.Value>newDefaultInstance(
                  com.netflix.conductor.proto.DynamicForkJoinTaskPb.internal_static_conductor_proto_DynamicForkJoinTask_InputEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  com.google.protobuf.Value.getDefaultInstance());
    }
    private com.google.protobuf.MapField<
        java.lang.String, com.google.protobuf.Value> input_;
    private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.Value>
    internalGetInput() {
      if (input_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            InputDefaultEntryHolder.defaultEntry);
      }
      return input_;
    }

    public int getInputCount() {
      return internalGetInput().getMap().size();
    }
    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; input = 4;</code>
     */

    @java.lang.Override
    public boolean containsInput(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetInput().getMap().containsKey(key);
    }
    /**
     * Use {@link #getInputMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.google.protobuf.Value> getInput() {
      return getInputMap();
    }
    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; input = 4;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, com.google.protobuf.Value> getInputMap() {
      return internalGetInput().getMap();
    }
    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; input = 4;</code>
     */
    @java.lang.Override

    public com.google.protobuf.Value getInputOrDefault(
        java.lang.String key,
        com.google.protobuf.Value defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.google.protobuf.Value> map =
          internalGetInput().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; input = 4;</code>
     */
    @java.lang.Override

    public com.google.protobuf.Value getInputOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.google.protobuf.Value> map =
          internalGetInput().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public static final int TYPE_FIELD_NUMBER = 5;
    private volatile java.lang.Object type_;
    /**
     * <code>string type = 5;</code>
     * @return The type.
     */
    @java.lang.Override
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      }
    }
    /**
     * <code>string type = 5;</code>
     * @return The bytes for type.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getTaskNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, taskName_);
      }
      if (!getWorkflowNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, workflowName_);
      }
      if (!getReferenceNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, referenceName_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetInput(),
          InputDefaultEntryHolder.defaultEntry,
          4);
      if (!getTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, type_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTaskNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, taskName_);
      }
      if (!getWorkflowNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, workflowName_);
      }
      if (!getReferenceNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, referenceName_);
      }
      for (java.util.Map.Entry<java.lang.String, com.google.protobuf.Value> entry
           : internalGetInput().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, com.google.protobuf.Value>
        input__ = InputDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(4, input__);
      }
      if (!getTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, type_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.netflix.conductor.proto.DynamicForkJoinTaskPb.DynamicForkJoinTask)) {
        return super.equals(obj);
      }
      com.netflix.conductor.proto.DynamicForkJoinTaskPb.DynamicForkJoinTask other = (com.netflix.conductor.proto.DynamicForkJoinTaskPb.DynamicForkJoinTask) obj;

      if (!getTaskName()
          .equals(other.getTaskName())) return false;
      if (!getWorkflowName()
          .equals(other.getWorkflowName())) return false;
      if (!getReferenceName()
          .equals(other.getReferenceName())) return false;
      if (!internalGetInput().equals(
          other.internalGetInput())) return false;
      if (!getType()
          .equals(other.getType())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TASK_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getTaskName().hashCode();
      hash = (37 * hash) + WORKFLOW_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getWorkflowName().hashCode();
      hash = (37 * hash) + REFERENCE_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getReferenceName().hashCode();
      if (!internalGetInput().getMap().isEmpty()) {
        hash = (37 * hash) + INPUT_FIELD_NUMBER;
        hash = (53 * hash) + internalGetInput().hashCode();
      }
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.netflix.conductor.proto.DynamicForkJoinTaskPb.DynamicForkJoinTask parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.netflix.conductor.proto.DynamicForkJoinTaskPb.DynamicForkJoinTask parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.netflix.conductor.proto.DynamicForkJoinTaskPb.DynamicForkJoinTask parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.netflix.conductor.proto.DynamicForkJoinTaskPb.DynamicForkJoinTask parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.netflix.conductor.proto.DynamicForkJoinTaskPb.DynamicForkJoinTask parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.netflix.conductor.proto.DynamicForkJoinTaskPb.DynamicForkJoinTask parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.netflix.conductor.proto.DynamicForkJoinTaskPb.DynamicForkJoinTask parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.netflix.conductor.proto.DynamicForkJoinTaskPb.DynamicForkJoinTask parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.netflix.conductor.proto.DynamicForkJoinTaskPb.DynamicForkJoinTask parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.netflix.conductor.proto.DynamicForkJoinTaskPb.DynamicForkJoinTask parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.netflix.conductor.proto.DynamicForkJoinTaskPb.DynamicForkJoinTask parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.netflix.conductor.proto.DynamicForkJoinTaskPb.DynamicForkJoinTask parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.netflix.conductor.proto.DynamicForkJoinTaskPb.DynamicForkJoinTask prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code conductor.proto.DynamicForkJoinTask}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:conductor.proto.DynamicForkJoinTask)
        com.netflix.conductor.proto.DynamicForkJoinTaskPb.DynamicForkJoinTaskOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.netflix.conductor.proto.DynamicForkJoinTaskPb.internal_static_conductor_proto_DynamicForkJoinTask_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 4:
            return internalGetInput();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 4:
            return internalGetMutableInput();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.netflix.conductor.proto.DynamicForkJoinTaskPb.internal_static_conductor_proto_DynamicForkJoinTask_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.netflix.conductor.proto.DynamicForkJoinTaskPb.DynamicForkJoinTask.class, com.netflix.conductor.proto.DynamicForkJoinTaskPb.DynamicForkJoinTask.Builder.class);
      }

      // Construct using com.netflix.conductor.proto.DynamicForkJoinTaskPb.DynamicForkJoinTask.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        taskName_ = "";

        workflowName_ = "";

        referenceName_ = "";

        internalGetMutableInput().clear();
        type_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.netflix.conductor.proto.DynamicForkJoinTaskPb.internal_static_conductor_proto_DynamicForkJoinTask_descriptor;
      }

      @java.lang.Override
      public com.netflix.conductor.proto.DynamicForkJoinTaskPb.DynamicForkJoinTask getDefaultInstanceForType() {
        return com.netflix.conductor.proto.DynamicForkJoinTaskPb.DynamicForkJoinTask.getDefaultInstance();
      }

      @java.lang.Override
      public com.netflix.conductor.proto.DynamicForkJoinTaskPb.DynamicForkJoinTask build() {
        com.netflix.conductor.proto.DynamicForkJoinTaskPb.DynamicForkJoinTask result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.netflix.conductor.proto.DynamicForkJoinTaskPb.DynamicForkJoinTask buildPartial() {
        com.netflix.conductor.proto.DynamicForkJoinTaskPb.DynamicForkJoinTask result = new com.netflix.conductor.proto.DynamicForkJoinTaskPb.DynamicForkJoinTask(this);
        int from_bitField0_ = bitField0_;
        result.taskName_ = taskName_;
        result.workflowName_ = workflowName_;
        result.referenceName_ = referenceName_;
        result.input_ = internalGetInput();
        result.input_.makeImmutable();
        result.type_ = type_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.netflix.conductor.proto.DynamicForkJoinTaskPb.DynamicForkJoinTask) {
          return mergeFrom((com.netflix.conductor.proto.DynamicForkJoinTaskPb.DynamicForkJoinTask)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.netflix.conductor.proto.DynamicForkJoinTaskPb.DynamicForkJoinTask other) {
        if (other == com.netflix.conductor.proto.DynamicForkJoinTaskPb.DynamicForkJoinTask.getDefaultInstance()) return this;
        if (!other.getTaskName().isEmpty()) {
          taskName_ = other.taskName_;
          onChanged();
        }
        if (!other.getWorkflowName().isEmpty()) {
          workflowName_ = other.workflowName_;
          onChanged();
        }
        if (!other.getReferenceName().isEmpty()) {
          referenceName_ = other.referenceName_;
          onChanged();
        }
        internalGetMutableInput().mergeFrom(
            other.internalGetInput());
        if (!other.getType().isEmpty()) {
          type_ = other.type_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.netflix.conductor.proto.DynamicForkJoinTaskPb.DynamicForkJoinTask parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.netflix.conductor.proto.DynamicForkJoinTaskPb.DynamicForkJoinTask) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object taskName_ = "";
      /**
       * <code>string task_name = 1;</code>
       * @return The taskName.
       */
      public java.lang.String getTaskName() {
        java.lang.Object ref = taskName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          taskName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string task_name = 1;</code>
       * @return The bytes for taskName.
       */
      public com.google.protobuf.ByteString
          getTaskNameBytes() {
        java.lang.Object ref = taskName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          taskName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string task_name = 1;</code>
       * @param value The taskName to set.
       * @return This builder for chaining.
       */
      public Builder setTaskName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        taskName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string task_name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTaskName() {
        
        taskName_ = getDefaultInstance().getTaskName();
        onChanged();
        return this;
      }
      /**
       * <code>string task_name = 1;</code>
       * @param value The bytes for taskName to set.
       * @return This builder for chaining.
       */
      public Builder setTaskNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        taskName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object workflowName_ = "";
      /**
       * <code>string workflow_name = 2;</code>
       * @return The workflowName.
       */
      public java.lang.String getWorkflowName() {
        java.lang.Object ref = workflowName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          workflowName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string workflow_name = 2;</code>
       * @return The bytes for workflowName.
       */
      public com.google.protobuf.ByteString
          getWorkflowNameBytes() {
        java.lang.Object ref = workflowName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          workflowName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string workflow_name = 2;</code>
       * @param value The workflowName to set.
       * @return This builder for chaining.
       */
      public Builder setWorkflowName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        workflowName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string workflow_name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearWorkflowName() {
        
        workflowName_ = getDefaultInstance().getWorkflowName();
        onChanged();
        return this;
      }
      /**
       * <code>string workflow_name = 2;</code>
       * @param value The bytes for workflowName to set.
       * @return This builder for chaining.
       */
      public Builder setWorkflowNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        workflowName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object referenceName_ = "";
      /**
       * <code>string reference_name = 3;</code>
       * @return The referenceName.
       */
      public java.lang.String getReferenceName() {
        java.lang.Object ref = referenceName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          referenceName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string reference_name = 3;</code>
       * @return The bytes for referenceName.
       */
      public com.google.protobuf.ByteString
          getReferenceNameBytes() {
        java.lang.Object ref = referenceName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          referenceName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string reference_name = 3;</code>
       * @param value The referenceName to set.
       * @return This builder for chaining.
       */
      public Builder setReferenceName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        referenceName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string reference_name = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearReferenceName() {
        
        referenceName_ = getDefaultInstance().getReferenceName();
        onChanged();
        return this;
      }
      /**
       * <code>string reference_name = 3;</code>
       * @param value The bytes for referenceName to set.
       * @return This builder for chaining.
       */
      public Builder setReferenceNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        referenceName_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, com.google.protobuf.Value> input_;
      private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.Value>
      internalGetInput() {
        if (input_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              InputDefaultEntryHolder.defaultEntry);
        }
        return input_;
      }
      private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.Value>
      internalGetMutableInput() {
        onChanged();;
        if (input_ == null) {
          input_ = com.google.protobuf.MapField.newMapField(
              InputDefaultEntryHolder.defaultEntry);
        }
        if (!input_.isMutable()) {
          input_ = input_.copy();
        }
        return input_;
      }

      public int getInputCount() {
        return internalGetInput().getMap().size();
      }
      /**
       * <code>map&lt;string, .google.protobuf.Value&gt; input = 4;</code>
       */

      @java.lang.Override
      public boolean containsInput(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetInput().getMap().containsKey(key);
      }
      /**
       * Use {@link #getInputMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, com.google.protobuf.Value> getInput() {
        return getInputMap();
      }
      /**
       * <code>map&lt;string, .google.protobuf.Value&gt; input = 4;</code>
       */
      @java.lang.Override

      public java.util.Map<java.lang.String, com.google.protobuf.Value> getInputMap() {
        return internalGetInput().getMap();
      }
      /**
       * <code>map&lt;string, .google.protobuf.Value&gt; input = 4;</code>
       */
      @java.lang.Override

      public com.google.protobuf.Value getInputOrDefault(
          java.lang.String key,
          com.google.protobuf.Value defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, com.google.protobuf.Value> map =
            internalGetInput().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, .google.protobuf.Value&gt; input = 4;</code>
       */
      @java.lang.Override

      public com.google.protobuf.Value getInputOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, com.google.protobuf.Value> map =
            internalGetInput().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearInput() {
        internalGetMutableInput().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, .google.protobuf.Value&gt; input = 4;</code>
       */

      public Builder removeInput(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableInput().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, com.google.protobuf.Value>
      getMutableInput() {
        return internalGetMutableInput().getMutableMap();
      }
      /**
       * <code>map&lt;string, .google.protobuf.Value&gt; input = 4;</code>
       */
      public Builder putInput(
          java.lang.String key,
          com.google.protobuf.Value value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableInput().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, .google.protobuf.Value&gt; input = 4;</code>
       */

      public Builder putAllInput(
          java.util.Map<java.lang.String, com.google.protobuf.Value> values) {
        internalGetMutableInput().getMutableMap()
            .putAll(values);
        return this;
      }

      private java.lang.Object type_ = "";
      /**
       * <code>string type = 5;</code>
       * @return The type.
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string type = 5;</code>
       * @return The bytes for type.
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string type = 5;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string type = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <code>string type = 5;</code>
       * @param value The bytes for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        type_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:conductor.proto.DynamicForkJoinTask)
    }

    // @@protoc_insertion_point(class_scope:conductor.proto.DynamicForkJoinTask)
    private static final com.netflix.conductor.proto.DynamicForkJoinTaskPb.DynamicForkJoinTask DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.netflix.conductor.proto.DynamicForkJoinTaskPb.DynamicForkJoinTask();
    }

    public static com.netflix.conductor.proto.DynamicForkJoinTaskPb.DynamicForkJoinTask getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DynamicForkJoinTask>
        PARSER = new com.google.protobuf.AbstractParser<DynamicForkJoinTask>() {
      @java.lang.Override
      public DynamicForkJoinTask parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DynamicForkJoinTask(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DynamicForkJoinTask> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DynamicForkJoinTask> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.netflix.conductor.proto.DynamicForkJoinTaskPb.DynamicForkJoinTask getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_conductor_proto_DynamicForkJoinTask_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_conductor_proto_DynamicForkJoinTask_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_conductor_proto_DynamicForkJoinTask_InputEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_conductor_proto_DynamicForkJoinTask_InputEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037model/dynamicforkjointask.proto\022\017condu" +
      "ctor.proto\032\034google/protobuf/struct.proto" +
      "\"\353\001\n\023DynamicForkJoinTask\022\021\n\ttask_name\030\001 " +
      "\001(\t\022\025\n\rworkflow_name\030\002 \001(\t\022\026\n\016reference_" +
      "name\030\003 \001(\t\022>\n\005input\030\004 \003(\0132/.conductor.pr" +
      "oto.DynamicForkJoinTask.InputEntry\022\014\n\004ty" +
      "pe\030\005 \001(\t\032D\n\nInputEntry\022\013\n\003key\030\001 \001(\t\022%\n\005v" +
      "alue\030\002 \001(\0132\026.google.protobuf.Value:\0028\001Bp" +
      "\n\033com.netflix.conductor.protoB\025DynamicFo" +
      "rkJoinTaskPbZ:github.com/netflix/conduct" +
      "or/client/gogrpc/conductor/modelb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.StructProto.getDescriptor(),
        });
    internal_static_conductor_proto_DynamicForkJoinTask_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_conductor_proto_DynamicForkJoinTask_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_conductor_proto_DynamicForkJoinTask_descriptor,
        new java.lang.String[] { "TaskName", "WorkflowName", "ReferenceName", "Input", "Type", });
    internal_static_conductor_proto_DynamicForkJoinTask_InputEntry_descriptor =
      internal_static_conductor_proto_DynamicForkJoinTask_descriptor.getNestedTypes().get(0);
    internal_static_conductor_proto_DynamicForkJoinTask_InputEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_conductor_proto_DynamicForkJoinTask_InputEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    com.google.protobuf.StructProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
