// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model/dynamicforkjointasklist.proto

package com.netflix.conductor.proto;

public final class DynamicForkJoinTaskListPb {
  private DynamicForkJoinTaskListPb() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DynamicForkJoinTaskListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:conductor.proto.DynamicForkJoinTaskList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .conductor.proto.DynamicForkJoinTask dynamic_tasks = 1;</code>
     */
    java.util.List<com.netflix.conductor.proto.DynamicForkJoinTaskPb.DynamicForkJoinTask> 
        getDynamicTasksList();
    /**
     * <code>repeated .conductor.proto.DynamicForkJoinTask dynamic_tasks = 1;</code>
     */
    com.netflix.conductor.proto.DynamicForkJoinTaskPb.DynamicForkJoinTask getDynamicTasks(int index);
    /**
     * <code>repeated .conductor.proto.DynamicForkJoinTask dynamic_tasks = 1;</code>
     */
    int getDynamicTasksCount();
    /**
     * <code>repeated .conductor.proto.DynamicForkJoinTask dynamic_tasks = 1;</code>
     */
    java.util.List<? extends com.netflix.conductor.proto.DynamicForkJoinTaskPb.DynamicForkJoinTaskOrBuilder> 
        getDynamicTasksOrBuilderList();
    /**
     * <code>repeated .conductor.proto.DynamicForkJoinTask dynamic_tasks = 1;</code>
     */
    com.netflix.conductor.proto.DynamicForkJoinTaskPb.DynamicForkJoinTaskOrBuilder getDynamicTasksOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code conductor.proto.DynamicForkJoinTaskList}
   */
  public static final class DynamicForkJoinTaskList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:conductor.proto.DynamicForkJoinTaskList)
      DynamicForkJoinTaskListOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DynamicForkJoinTaskList.newBuilder() to construct.
    private DynamicForkJoinTaskList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DynamicForkJoinTaskList() {
      dynamicTasks_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new DynamicForkJoinTaskList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DynamicForkJoinTaskList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                dynamicTasks_ = new java.util.ArrayList<com.netflix.conductor.proto.DynamicForkJoinTaskPb.DynamicForkJoinTask>();
                mutable_bitField0_ |= 0x00000001;
              }
              dynamicTasks_.add(
                  input.readMessage(com.netflix.conductor.proto.DynamicForkJoinTaskPb.DynamicForkJoinTask.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          dynamicTasks_ = java.util.Collections.unmodifiableList(dynamicTasks_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.netflix.conductor.proto.DynamicForkJoinTaskListPb.internal_static_conductor_proto_DynamicForkJoinTaskList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.netflix.conductor.proto.DynamicForkJoinTaskListPb.internal_static_conductor_proto_DynamicForkJoinTaskList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.netflix.conductor.proto.DynamicForkJoinTaskListPb.DynamicForkJoinTaskList.class, com.netflix.conductor.proto.DynamicForkJoinTaskListPb.DynamicForkJoinTaskList.Builder.class);
    }

    public static final int DYNAMIC_TASKS_FIELD_NUMBER = 1;
    private java.util.List<com.netflix.conductor.proto.DynamicForkJoinTaskPb.DynamicForkJoinTask> dynamicTasks_;
    /**
     * <code>repeated .conductor.proto.DynamicForkJoinTask dynamic_tasks = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.netflix.conductor.proto.DynamicForkJoinTaskPb.DynamicForkJoinTask> getDynamicTasksList() {
      return dynamicTasks_;
    }
    /**
     * <code>repeated .conductor.proto.DynamicForkJoinTask dynamic_tasks = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.netflix.conductor.proto.DynamicForkJoinTaskPb.DynamicForkJoinTaskOrBuilder> 
        getDynamicTasksOrBuilderList() {
      return dynamicTasks_;
    }
    /**
     * <code>repeated .conductor.proto.DynamicForkJoinTask dynamic_tasks = 1;</code>
     */
    @java.lang.Override
    public int getDynamicTasksCount() {
      return dynamicTasks_.size();
    }
    /**
     * <code>repeated .conductor.proto.DynamicForkJoinTask dynamic_tasks = 1;</code>
     */
    @java.lang.Override
    public com.netflix.conductor.proto.DynamicForkJoinTaskPb.DynamicForkJoinTask getDynamicTasks(int index) {
      return dynamicTasks_.get(index);
    }
    /**
     * <code>repeated .conductor.proto.DynamicForkJoinTask dynamic_tasks = 1;</code>
     */
    @java.lang.Override
    public com.netflix.conductor.proto.DynamicForkJoinTaskPb.DynamicForkJoinTaskOrBuilder getDynamicTasksOrBuilder(
        int index) {
      return dynamicTasks_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < dynamicTasks_.size(); i++) {
        output.writeMessage(1, dynamicTasks_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < dynamicTasks_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, dynamicTasks_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.netflix.conductor.proto.DynamicForkJoinTaskListPb.DynamicForkJoinTaskList)) {
        return super.equals(obj);
      }
      com.netflix.conductor.proto.DynamicForkJoinTaskListPb.DynamicForkJoinTaskList other = (com.netflix.conductor.proto.DynamicForkJoinTaskListPb.DynamicForkJoinTaskList) obj;

      if (!getDynamicTasksList()
          .equals(other.getDynamicTasksList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getDynamicTasksCount() > 0) {
        hash = (37 * hash) + DYNAMIC_TASKS_FIELD_NUMBER;
        hash = (53 * hash) + getDynamicTasksList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.netflix.conductor.proto.DynamicForkJoinTaskListPb.DynamicForkJoinTaskList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.netflix.conductor.proto.DynamicForkJoinTaskListPb.DynamicForkJoinTaskList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.netflix.conductor.proto.DynamicForkJoinTaskListPb.DynamicForkJoinTaskList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.netflix.conductor.proto.DynamicForkJoinTaskListPb.DynamicForkJoinTaskList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.netflix.conductor.proto.DynamicForkJoinTaskListPb.DynamicForkJoinTaskList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.netflix.conductor.proto.DynamicForkJoinTaskListPb.DynamicForkJoinTaskList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.netflix.conductor.proto.DynamicForkJoinTaskListPb.DynamicForkJoinTaskList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.netflix.conductor.proto.DynamicForkJoinTaskListPb.DynamicForkJoinTaskList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.netflix.conductor.proto.DynamicForkJoinTaskListPb.DynamicForkJoinTaskList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.netflix.conductor.proto.DynamicForkJoinTaskListPb.DynamicForkJoinTaskList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.netflix.conductor.proto.DynamicForkJoinTaskListPb.DynamicForkJoinTaskList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.netflix.conductor.proto.DynamicForkJoinTaskListPb.DynamicForkJoinTaskList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.netflix.conductor.proto.DynamicForkJoinTaskListPb.DynamicForkJoinTaskList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code conductor.proto.DynamicForkJoinTaskList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:conductor.proto.DynamicForkJoinTaskList)
        com.netflix.conductor.proto.DynamicForkJoinTaskListPb.DynamicForkJoinTaskListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.netflix.conductor.proto.DynamicForkJoinTaskListPb.internal_static_conductor_proto_DynamicForkJoinTaskList_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.netflix.conductor.proto.DynamicForkJoinTaskListPb.internal_static_conductor_proto_DynamicForkJoinTaskList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.netflix.conductor.proto.DynamicForkJoinTaskListPb.DynamicForkJoinTaskList.class, com.netflix.conductor.proto.DynamicForkJoinTaskListPb.DynamicForkJoinTaskList.Builder.class);
      }

      // Construct using com.netflix.conductor.proto.DynamicForkJoinTaskListPb.DynamicForkJoinTaskList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getDynamicTasksFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (dynamicTasksBuilder_ == null) {
          dynamicTasks_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          dynamicTasksBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.netflix.conductor.proto.DynamicForkJoinTaskListPb.internal_static_conductor_proto_DynamicForkJoinTaskList_descriptor;
      }

      @java.lang.Override
      public com.netflix.conductor.proto.DynamicForkJoinTaskListPb.DynamicForkJoinTaskList getDefaultInstanceForType() {
        return com.netflix.conductor.proto.DynamicForkJoinTaskListPb.DynamicForkJoinTaskList.getDefaultInstance();
      }

      @java.lang.Override
      public com.netflix.conductor.proto.DynamicForkJoinTaskListPb.DynamicForkJoinTaskList build() {
        com.netflix.conductor.proto.DynamicForkJoinTaskListPb.DynamicForkJoinTaskList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.netflix.conductor.proto.DynamicForkJoinTaskListPb.DynamicForkJoinTaskList buildPartial() {
        com.netflix.conductor.proto.DynamicForkJoinTaskListPb.DynamicForkJoinTaskList result = new com.netflix.conductor.proto.DynamicForkJoinTaskListPb.DynamicForkJoinTaskList(this);
        int from_bitField0_ = bitField0_;
        if (dynamicTasksBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            dynamicTasks_ = java.util.Collections.unmodifiableList(dynamicTasks_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.dynamicTasks_ = dynamicTasks_;
        } else {
          result.dynamicTasks_ = dynamicTasksBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.netflix.conductor.proto.DynamicForkJoinTaskListPb.DynamicForkJoinTaskList) {
          return mergeFrom((com.netflix.conductor.proto.DynamicForkJoinTaskListPb.DynamicForkJoinTaskList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.netflix.conductor.proto.DynamicForkJoinTaskListPb.DynamicForkJoinTaskList other) {
        if (other == com.netflix.conductor.proto.DynamicForkJoinTaskListPb.DynamicForkJoinTaskList.getDefaultInstance()) return this;
        if (dynamicTasksBuilder_ == null) {
          if (!other.dynamicTasks_.isEmpty()) {
            if (dynamicTasks_.isEmpty()) {
              dynamicTasks_ = other.dynamicTasks_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureDynamicTasksIsMutable();
              dynamicTasks_.addAll(other.dynamicTasks_);
            }
            onChanged();
          }
        } else {
          if (!other.dynamicTasks_.isEmpty()) {
            if (dynamicTasksBuilder_.isEmpty()) {
              dynamicTasksBuilder_.dispose();
              dynamicTasksBuilder_ = null;
              dynamicTasks_ = other.dynamicTasks_;
              bitField0_ = (bitField0_ & ~0x00000001);
              dynamicTasksBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getDynamicTasksFieldBuilder() : null;
            } else {
              dynamicTasksBuilder_.addAllMessages(other.dynamicTasks_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.netflix.conductor.proto.DynamicForkJoinTaskListPb.DynamicForkJoinTaskList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.netflix.conductor.proto.DynamicForkJoinTaskListPb.DynamicForkJoinTaskList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.netflix.conductor.proto.DynamicForkJoinTaskPb.DynamicForkJoinTask> dynamicTasks_ =
        java.util.Collections.emptyList();
      private void ensureDynamicTasksIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          dynamicTasks_ = new java.util.ArrayList<com.netflix.conductor.proto.DynamicForkJoinTaskPb.DynamicForkJoinTask>(dynamicTasks_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.netflix.conductor.proto.DynamicForkJoinTaskPb.DynamicForkJoinTask, com.netflix.conductor.proto.DynamicForkJoinTaskPb.DynamicForkJoinTask.Builder, com.netflix.conductor.proto.DynamicForkJoinTaskPb.DynamicForkJoinTaskOrBuilder> dynamicTasksBuilder_;

      /**
       * <code>repeated .conductor.proto.DynamicForkJoinTask dynamic_tasks = 1;</code>
       */
      public java.util.List<com.netflix.conductor.proto.DynamicForkJoinTaskPb.DynamicForkJoinTask> getDynamicTasksList() {
        if (dynamicTasksBuilder_ == null) {
          return java.util.Collections.unmodifiableList(dynamicTasks_);
        } else {
          return dynamicTasksBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .conductor.proto.DynamicForkJoinTask dynamic_tasks = 1;</code>
       */
      public int getDynamicTasksCount() {
        if (dynamicTasksBuilder_ == null) {
          return dynamicTasks_.size();
        } else {
          return dynamicTasksBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .conductor.proto.DynamicForkJoinTask dynamic_tasks = 1;</code>
       */
      public com.netflix.conductor.proto.DynamicForkJoinTaskPb.DynamicForkJoinTask getDynamicTasks(int index) {
        if (dynamicTasksBuilder_ == null) {
          return dynamicTasks_.get(index);
        } else {
          return dynamicTasksBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .conductor.proto.DynamicForkJoinTask dynamic_tasks = 1;</code>
       */
      public Builder setDynamicTasks(
          int index, com.netflix.conductor.proto.DynamicForkJoinTaskPb.DynamicForkJoinTask value) {
        if (dynamicTasksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDynamicTasksIsMutable();
          dynamicTasks_.set(index, value);
          onChanged();
        } else {
          dynamicTasksBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .conductor.proto.DynamicForkJoinTask dynamic_tasks = 1;</code>
       */
      public Builder setDynamicTasks(
          int index, com.netflix.conductor.proto.DynamicForkJoinTaskPb.DynamicForkJoinTask.Builder builderForValue) {
        if (dynamicTasksBuilder_ == null) {
          ensureDynamicTasksIsMutable();
          dynamicTasks_.set(index, builderForValue.build());
          onChanged();
        } else {
          dynamicTasksBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .conductor.proto.DynamicForkJoinTask dynamic_tasks = 1;</code>
       */
      public Builder addDynamicTasks(com.netflix.conductor.proto.DynamicForkJoinTaskPb.DynamicForkJoinTask value) {
        if (dynamicTasksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDynamicTasksIsMutable();
          dynamicTasks_.add(value);
          onChanged();
        } else {
          dynamicTasksBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .conductor.proto.DynamicForkJoinTask dynamic_tasks = 1;</code>
       */
      public Builder addDynamicTasks(
          int index, com.netflix.conductor.proto.DynamicForkJoinTaskPb.DynamicForkJoinTask value) {
        if (dynamicTasksBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDynamicTasksIsMutable();
          dynamicTasks_.add(index, value);
          onChanged();
        } else {
          dynamicTasksBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .conductor.proto.DynamicForkJoinTask dynamic_tasks = 1;</code>
       */
      public Builder addDynamicTasks(
          com.netflix.conductor.proto.DynamicForkJoinTaskPb.DynamicForkJoinTask.Builder builderForValue) {
        if (dynamicTasksBuilder_ == null) {
          ensureDynamicTasksIsMutable();
          dynamicTasks_.add(builderForValue.build());
          onChanged();
        } else {
          dynamicTasksBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .conductor.proto.DynamicForkJoinTask dynamic_tasks = 1;</code>
       */
      public Builder addDynamicTasks(
          int index, com.netflix.conductor.proto.DynamicForkJoinTaskPb.DynamicForkJoinTask.Builder builderForValue) {
        if (dynamicTasksBuilder_ == null) {
          ensureDynamicTasksIsMutable();
          dynamicTasks_.add(index, builderForValue.build());
          onChanged();
        } else {
          dynamicTasksBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .conductor.proto.DynamicForkJoinTask dynamic_tasks = 1;</code>
       */
      public Builder addAllDynamicTasks(
          java.lang.Iterable<? extends com.netflix.conductor.proto.DynamicForkJoinTaskPb.DynamicForkJoinTask> values) {
        if (dynamicTasksBuilder_ == null) {
          ensureDynamicTasksIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, dynamicTasks_);
          onChanged();
        } else {
          dynamicTasksBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .conductor.proto.DynamicForkJoinTask dynamic_tasks = 1;</code>
       */
      public Builder clearDynamicTasks() {
        if (dynamicTasksBuilder_ == null) {
          dynamicTasks_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          dynamicTasksBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .conductor.proto.DynamicForkJoinTask dynamic_tasks = 1;</code>
       */
      public Builder removeDynamicTasks(int index) {
        if (dynamicTasksBuilder_ == null) {
          ensureDynamicTasksIsMutable();
          dynamicTasks_.remove(index);
          onChanged();
        } else {
          dynamicTasksBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .conductor.proto.DynamicForkJoinTask dynamic_tasks = 1;</code>
       */
      public com.netflix.conductor.proto.DynamicForkJoinTaskPb.DynamicForkJoinTask.Builder getDynamicTasksBuilder(
          int index) {
        return getDynamicTasksFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .conductor.proto.DynamicForkJoinTask dynamic_tasks = 1;</code>
       */
      public com.netflix.conductor.proto.DynamicForkJoinTaskPb.DynamicForkJoinTaskOrBuilder getDynamicTasksOrBuilder(
          int index) {
        if (dynamicTasksBuilder_ == null) {
          return dynamicTasks_.get(index);  } else {
          return dynamicTasksBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .conductor.proto.DynamicForkJoinTask dynamic_tasks = 1;</code>
       */
      public java.util.List<? extends com.netflix.conductor.proto.DynamicForkJoinTaskPb.DynamicForkJoinTaskOrBuilder> 
           getDynamicTasksOrBuilderList() {
        if (dynamicTasksBuilder_ != null) {
          return dynamicTasksBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(dynamicTasks_);
        }
      }
      /**
       * <code>repeated .conductor.proto.DynamicForkJoinTask dynamic_tasks = 1;</code>
       */
      public com.netflix.conductor.proto.DynamicForkJoinTaskPb.DynamicForkJoinTask.Builder addDynamicTasksBuilder() {
        return getDynamicTasksFieldBuilder().addBuilder(
            com.netflix.conductor.proto.DynamicForkJoinTaskPb.DynamicForkJoinTask.getDefaultInstance());
      }
      /**
       * <code>repeated .conductor.proto.DynamicForkJoinTask dynamic_tasks = 1;</code>
       */
      public com.netflix.conductor.proto.DynamicForkJoinTaskPb.DynamicForkJoinTask.Builder addDynamicTasksBuilder(
          int index) {
        return getDynamicTasksFieldBuilder().addBuilder(
            index, com.netflix.conductor.proto.DynamicForkJoinTaskPb.DynamicForkJoinTask.getDefaultInstance());
      }
      /**
       * <code>repeated .conductor.proto.DynamicForkJoinTask dynamic_tasks = 1;</code>
       */
      public java.util.List<com.netflix.conductor.proto.DynamicForkJoinTaskPb.DynamicForkJoinTask.Builder> 
           getDynamicTasksBuilderList() {
        return getDynamicTasksFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.netflix.conductor.proto.DynamicForkJoinTaskPb.DynamicForkJoinTask, com.netflix.conductor.proto.DynamicForkJoinTaskPb.DynamicForkJoinTask.Builder, com.netflix.conductor.proto.DynamicForkJoinTaskPb.DynamicForkJoinTaskOrBuilder> 
          getDynamicTasksFieldBuilder() {
        if (dynamicTasksBuilder_ == null) {
          dynamicTasksBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.netflix.conductor.proto.DynamicForkJoinTaskPb.DynamicForkJoinTask, com.netflix.conductor.proto.DynamicForkJoinTaskPb.DynamicForkJoinTask.Builder, com.netflix.conductor.proto.DynamicForkJoinTaskPb.DynamicForkJoinTaskOrBuilder>(
                  dynamicTasks_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          dynamicTasks_ = null;
        }
        return dynamicTasksBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:conductor.proto.DynamicForkJoinTaskList)
    }

    // @@protoc_insertion_point(class_scope:conductor.proto.DynamicForkJoinTaskList)
    private static final com.netflix.conductor.proto.DynamicForkJoinTaskListPb.DynamicForkJoinTaskList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.netflix.conductor.proto.DynamicForkJoinTaskListPb.DynamicForkJoinTaskList();
    }

    public static com.netflix.conductor.proto.DynamicForkJoinTaskListPb.DynamicForkJoinTaskList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DynamicForkJoinTaskList>
        PARSER = new com.google.protobuf.AbstractParser<DynamicForkJoinTaskList>() {
      @java.lang.Override
      public DynamicForkJoinTaskList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DynamicForkJoinTaskList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DynamicForkJoinTaskList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DynamicForkJoinTaskList> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.netflix.conductor.proto.DynamicForkJoinTaskListPb.DynamicForkJoinTaskList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_conductor_proto_DynamicForkJoinTaskList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_conductor_proto_DynamicForkJoinTaskList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n#model/dynamicforkjointasklist.proto\022\017c" +
      "onductor.proto\032\037model/dynamicforkjointas" +
      "k.proto\"V\n\027DynamicForkJoinTaskList\022;\n\rdy" +
      "namic_tasks\030\001 \003(\0132$.conductor.proto.Dyna" +
      "micForkJoinTaskBt\n\033com.netflix.conductor" +
      ".protoB\031DynamicForkJoinTaskListPbZ:githu" +
      "b.com/netflix/conductor/client/gogrpc/co" +
      "nductor/modelb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.netflix.conductor.proto.DynamicForkJoinTaskPb.getDescriptor(),
        });
    internal_static_conductor_proto_DynamicForkJoinTaskList_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_conductor_proto_DynamicForkJoinTaskList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_conductor_proto_DynamicForkJoinTaskList_descriptor,
        new java.lang.String[] { "DynamicTasks", });
    com.netflix.conductor.proto.DynamicForkJoinTaskPb.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
