// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model/eventexecution.proto

package com.netflix.conductor.proto;

public final class EventExecutionPb {
  private EventExecutionPb() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface EventExecutionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:conductor.proto.EventExecution)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    java.lang.String getId();
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>string message_id = 2;</code>
     * @return The messageId.
     */
    java.lang.String getMessageId();
    /**
     * <code>string message_id = 2;</code>
     * @return The bytes for messageId.
     */
    com.google.protobuf.ByteString
        getMessageIdBytes();

    /**
     * <code>string name = 3;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 3;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string event = 4;</code>
     * @return The event.
     */
    java.lang.String getEvent();
    /**
     * <code>string event = 4;</code>
     * @return The bytes for event.
     */
    com.google.protobuf.ByteString
        getEventBytes();

    /**
     * <code>int64 created = 5;</code>
     * @return The created.
     */
    long getCreated();

    /**
     * <code>.conductor.proto.EventExecution.Status status = 6;</code>
     * @return The enum numeric value on the wire for status.
     */
    int getStatusValue();
    /**
     * <code>.conductor.proto.EventExecution.Status status = 6;</code>
     * @return The status.
     */
    com.netflix.conductor.proto.EventExecutionPb.EventExecution.Status getStatus();

    /**
     * <code>.conductor.proto.EventHandler.Action.Type action = 7;</code>
     * @return The enum numeric value on the wire for action.
     */
    int getActionValue();
    /**
     * <code>.conductor.proto.EventHandler.Action.Type action = 7;</code>
     * @return The action.
     */
    com.netflix.conductor.proto.EventHandlerPb.EventHandler.Action.Type getAction();

    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; output = 8;</code>
     */
    int getOutputCount();
    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; output = 8;</code>
     */
    boolean containsOutput(
        java.lang.String key);
    /**
     * Use {@link #getOutputMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, com.google.protobuf.Value>
    getOutput();
    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; output = 8;</code>
     */
    java.util.Map<java.lang.String, com.google.protobuf.Value>
    getOutputMap();
    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; output = 8;</code>
     */

    com.google.protobuf.Value getOutputOrDefault(
        java.lang.String key,
        com.google.protobuf.Value defaultValue);
    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; output = 8;</code>
     */

    com.google.protobuf.Value getOutputOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code conductor.proto.EventExecution}
   */
  public static final class EventExecution extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:conductor.proto.EventExecution)
      EventExecutionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use EventExecution.newBuilder() to construct.
    private EventExecution(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EventExecution() {
      id_ = "";
      messageId_ = "";
      name_ = "";
      event_ = "";
      status_ = 0;
      action_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new EventExecution();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private EventExecution(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              messageId_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              event_ = s;
              break;
            }
            case 40: {

              created_ = input.readInt64();
              break;
            }
            case 48: {
              int rawValue = input.readEnum();

              status_ = rawValue;
              break;
            }
            case 56: {
              int rawValue = input.readEnum();

              action_ = rawValue;
              break;
            }
            case 66: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                output_ = com.google.protobuf.MapField.newMapField(
                    OutputDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<java.lang.String, com.google.protobuf.Value>
              output__ = input.readMessage(
                  OutputDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              output_.getMutableMap().put(
                  output__.getKey(), output__.getValue());
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.netflix.conductor.proto.EventExecutionPb.internal_static_conductor_proto_EventExecution_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 8:
          return internalGetOutput();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.netflix.conductor.proto.EventExecutionPb.internal_static_conductor_proto_EventExecution_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.netflix.conductor.proto.EventExecutionPb.EventExecution.class, com.netflix.conductor.proto.EventExecutionPb.EventExecution.Builder.class);
    }

    /**
     * Protobuf enum {@code conductor.proto.EventExecution.Status}
     */
    public enum Status
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>IN_PROGRESS = 0;</code>
       */
      IN_PROGRESS(0),
      /**
       * <code>COMPLETED = 1;</code>
       */
      COMPLETED(1),
      /**
       * <code>FAILED = 2;</code>
       */
      FAILED(2),
      /**
       * <code>SKIPPED = 3;</code>
       */
      SKIPPED(3),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>IN_PROGRESS = 0;</code>
       */
      public static final int IN_PROGRESS_VALUE = 0;
      /**
       * <code>COMPLETED = 1;</code>
       */
      public static final int COMPLETED_VALUE = 1;
      /**
       * <code>FAILED = 2;</code>
       */
      public static final int FAILED_VALUE = 2;
      /**
       * <code>SKIPPED = 3;</code>
       */
      public static final int SKIPPED_VALUE = 3;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Status valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static Status forNumber(int value) {
        switch (value) {
          case 0: return IN_PROGRESS;
          case 1: return COMPLETED;
          case 2: return FAILED;
          case 3: return SKIPPED;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Status>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Status> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Status>() {
              public Status findValueByNumber(int number) {
                return Status.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.netflix.conductor.proto.EventExecutionPb.EventExecution.getDescriptor().getEnumTypes().get(0);
      }

      private static final Status[] VALUES = values();

      public static Status valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Status(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:conductor.proto.EventExecution.Status)
    }

    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MESSAGE_ID_FIELD_NUMBER = 2;
    private volatile java.lang.Object messageId_;
    /**
     * <code>string message_id = 2;</code>
     * @return The messageId.
     */
    @java.lang.Override
    public java.lang.String getMessageId() {
      java.lang.Object ref = messageId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        messageId_ = s;
        return s;
      }
    }
    /**
     * <code>string message_id = 2;</code>
     * @return The bytes for messageId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMessageIdBytes() {
      java.lang.Object ref = messageId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        messageId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 3;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 3;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EVENT_FIELD_NUMBER = 4;
    private volatile java.lang.Object event_;
    /**
     * <code>string event = 4;</code>
     * @return The event.
     */
    @java.lang.Override
    public java.lang.String getEvent() {
      java.lang.Object ref = event_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        event_ = s;
        return s;
      }
    }
    /**
     * <code>string event = 4;</code>
     * @return The bytes for event.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEventBytes() {
      java.lang.Object ref = event_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        event_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CREATED_FIELD_NUMBER = 5;
    private long created_;
    /**
     * <code>int64 created = 5;</code>
     * @return The created.
     */
    @java.lang.Override
    public long getCreated() {
      return created_;
    }

    public static final int STATUS_FIELD_NUMBER = 6;
    private int status_;
    /**
     * <code>.conductor.proto.EventExecution.Status status = 6;</code>
     * @return The enum numeric value on the wire for status.
     */
    @java.lang.Override public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.conductor.proto.EventExecution.Status status = 6;</code>
     * @return The status.
     */
    @java.lang.Override public com.netflix.conductor.proto.EventExecutionPb.EventExecution.Status getStatus() {
      @SuppressWarnings("deprecation")
      com.netflix.conductor.proto.EventExecutionPb.EventExecution.Status result = com.netflix.conductor.proto.EventExecutionPb.EventExecution.Status.valueOf(status_);
      return result == null ? com.netflix.conductor.proto.EventExecutionPb.EventExecution.Status.UNRECOGNIZED : result;
    }

    public static final int ACTION_FIELD_NUMBER = 7;
    private int action_;
    /**
     * <code>.conductor.proto.EventHandler.Action.Type action = 7;</code>
     * @return The enum numeric value on the wire for action.
     */
    @java.lang.Override public int getActionValue() {
      return action_;
    }
    /**
     * <code>.conductor.proto.EventHandler.Action.Type action = 7;</code>
     * @return The action.
     */
    @java.lang.Override public com.netflix.conductor.proto.EventHandlerPb.EventHandler.Action.Type getAction() {
      @SuppressWarnings("deprecation")
      com.netflix.conductor.proto.EventHandlerPb.EventHandler.Action.Type result = com.netflix.conductor.proto.EventHandlerPb.EventHandler.Action.Type.valueOf(action_);
      return result == null ? com.netflix.conductor.proto.EventHandlerPb.EventHandler.Action.Type.UNRECOGNIZED : result;
    }

    public static final int OUTPUT_FIELD_NUMBER = 8;
    private static final class OutputDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, com.google.protobuf.Value> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, com.google.protobuf.Value>newDefaultInstance(
                  com.netflix.conductor.proto.EventExecutionPb.internal_static_conductor_proto_EventExecution_OutputEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  com.google.protobuf.Value.getDefaultInstance());
    }
    private com.google.protobuf.MapField<
        java.lang.String, com.google.protobuf.Value> output_;
    private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.Value>
    internalGetOutput() {
      if (output_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            OutputDefaultEntryHolder.defaultEntry);
      }
      return output_;
    }

    public int getOutputCount() {
      return internalGetOutput().getMap().size();
    }
    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; output = 8;</code>
     */

    @java.lang.Override
    public boolean containsOutput(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetOutput().getMap().containsKey(key);
    }
    /**
     * Use {@link #getOutputMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.google.protobuf.Value> getOutput() {
      return getOutputMap();
    }
    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; output = 8;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, com.google.protobuf.Value> getOutputMap() {
      return internalGetOutput().getMap();
    }
    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; output = 8;</code>
     */
    @java.lang.Override

    public com.google.protobuf.Value getOutputOrDefault(
        java.lang.String key,
        com.google.protobuf.Value defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.google.protobuf.Value> map =
          internalGetOutput().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; output = 8;</code>
     */
    @java.lang.Override

    public com.google.protobuf.Value getOutputOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.google.protobuf.Value> map =
          internalGetOutput().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (!getMessageIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, messageId_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, name_);
      }
      if (!getEventBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, event_);
      }
      if (created_ != 0L) {
        output.writeInt64(5, created_);
      }
      if (status_ != com.netflix.conductor.proto.EventExecutionPb.EventExecution.Status.IN_PROGRESS.getNumber()) {
        output.writeEnum(6, status_);
      }
      if (action_ != com.netflix.conductor.proto.EventHandlerPb.EventHandler.Action.Type.START_WORKFLOW.getNumber()) {
        output.writeEnum(7, action_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetOutput(),
          OutputDefaultEntryHolder.defaultEntry,
          8);
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (!getMessageIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, messageId_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, name_);
      }
      if (!getEventBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, event_);
      }
      if (created_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, created_);
      }
      if (status_ != com.netflix.conductor.proto.EventExecutionPb.EventExecution.Status.IN_PROGRESS.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(6, status_);
      }
      if (action_ != com.netflix.conductor.proto.EventHandlerPb.EventHandler.Action.Type.START_WORKFLOW.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(7, action_);
      }
      for (java.util.Map.Entry<java.lang.String, com.google.protobuf.Value> entry
           : internalGetOutput().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, com.google.protobuf.Value>
        output__ = OutputDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(8, output__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.netflix.conductor.proto.EventExecutionPb.EventExecution)) {
        return super.equals(obj);
      }
      com.netflix.conductor.proto.EventExecutionPb.EventExecution other = (com.netflix.conductor.proto.EventExecutionPb.EventExecution) obj;

      if (!getId()
          .equals(other.getId())) return false;
      if (!getMessageId()
          .equals(other.getMessageId())) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (!getEvent()
          .equals(other.getEvent())) return false;
      if (getCreated()
          != other.getCreated()) return false;
      if (status_ != other.status_) return false;
      if (action_ != other.action_) return false;
      if (!internalGetOutput().equals(
          other.internalGetOutput())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + MESSAGE_ID_FIELD_NUMBER;
      hash = (53 * hash) + getMessageId().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + EVENT_FIELD_NUMBER;
      hash = (53 * hash) + getEvent().hashCode();
      hash = (37 * hash) + CREATED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCreated());
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + status_;
      hash = (37 * hash) + ACTION_FIELD_NUMBER;
      hash = (53 * hash) + action_;
      if (!internalGetOutput().getMap().isEmpty()) {
        hash = (37 * hash) + OUTPUT_FIELD_NUMBER;
        hash = (53 * hash) + internalGetOutput().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.netflix.conductor.proto.EventExecutionPb.EventExecution parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.netflix.conductor.proto.EventExecutionPb.EventExecution parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.netflix.conductor.proto.EventExecutionPb.EventExecution parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.netflix.conductor.proto.EventExecutionPb.EventExecution parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.netflix.conductor.proto.EventExecutionPb.EventExecution parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.netflix.conductor.proto.EventExecutionPb.EventExecution parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.netflix.conductor.proto.EventExecutionPb.EventExecution parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.netflix.conductor.proto.EventExecutionPb.EventExecution parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.netflix.conductor.proto.EventExecutionPb.EventExecution parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.netflix.conductor.proto.EventExecutionPb.EventExecution parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.netflix.conductor.proto.EventExecutionPb.EventExecution parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.netflix.conductor.proto.EventExecutionPb.EventExecution parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.netflix.conductor.proto.EventExecutionPb.EventExecution prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code conductor.proto.EventExecution}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:conductor.proto.EventExecution)
        com.netflix.conductor.proto.EventExecutionPb.EventExecutionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.netflix.conductor.proto.EventExecutionPb.internal_static_conductor_proto_EventExecution_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 8:
            return internalGetOutput();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 8:
            return internalGetMutableOutput();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.netflix.conductor.proto.EventExecutionPb.internal_static_conductor_proto_EventExecution_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.netflix.conductor.proto.EventExecutionPb.EventExecution.class, com.netflix.conductor.proto.EventExecutionPb.EventExecution.Builder.class);
      }

      // Construct using com.netflix.conductor.proto.EventExecutionPb.EventExecution.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = "";

        messageId_ = "";

        name_ = "";

        event_ = "";

        created_ = 0L;

        status_ = 0;

        action_ = 0;

        internalGetMutableOutput().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.netflix.conductor.proto.EventExecutionPb.internal_static_conductor_proto_EventExecution_descriptor;
      }

      @java.lang.Override
      public com.netflix.conductor.proto.EventExecutionPb.EventExecution getDefaultInstanceForType() {
        return com.netflix.conductor.proto.EventExecutionPb.EventExecution.getDefaultInstance();
      }

      @java.lang.Override
      public com.netflix.conductor.proto.EventExecutionPb.EventExecution build() {
        com.netflix.conductor.proto.EventExecutionPb.EventExecution result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.netflix.conductor.proto.EventExecutionPb.EventExecution buildPartial() {
        com.netflix.conductor.proto.EventExecutionPb.EventExecution result = new com.netflix.conductor.proto.EventExecutionPb.EventExecution(this);
        int from_bitField0_ = bitField0_;
        result.id_ = id_;
        result.messageId_ = messageId_;
        result.name_ = name_;
        result.event_ = event_;
        result.created_ = created_;
        result.status_ = status_;
        result.action_ = action_;
        result.output_ = internalGetOutput();
        result.output_.makeImmutable();
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.netflix.conductor.proto.EventExecutionPb.EventExecution) {
          return mergeFrom((com.netflix.conductor.proto.EventExecutionPb.EventExecution)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.netflix.conductor.proto.EventExecutionPb.EventExecution other) {
        if (other == com.netflix.conductor.proto.EventExecutionPb.EventExecution.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (!other.getMessageId().isEmpty()) {
          messageId_ = other.messageId_;
          onChanged();
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getEvent().isEmpty()) {
          event_ = other.event_;
          onChanged();
        }
        if (other.getCreated() != 0L) {
          setCreated(other.getCreated());
        }
        if (other.status_ != 0) {
          setStatusValue(other.getStatusValue());
        }
        if (other.action_ != 0) {
          setActionValue(other.getActionValue());
        }
        internalGetMutableOutput().mergeFrom(
            other.internalGetOutput());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.netflix.conductor.proto.EventExecutionPb.EventExecution parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.netflix.conductor.proto.EventExecutionPb.EventExecution) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 1;</code>
       * @return The id.
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @return The bytes for id.
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object messageId_ = "";
      /**
       * <code>string message_id = 2;</code>
       * @return The messageId.
       */
      public java.lang.String getMessageId() {
        java.lang.Object ref = messageId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          messageId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string message_id = 2;</code>
       * @return The bytes for messageId.
       */
      public com.google.protobuf.ByteString
          getMessageIdBytes() {
        java.lang.Object ref = messageId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          messageId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string message_id = 2;</code>
       * @param value The messageId to set.
       * @return This builder for chaining.
       */
      public Builder setMessageId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        messageId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string message_id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessageId() {
        
        messageId_ = getDefaultInstance().getMessageId();
        onChanged();
        return this;
      }
      /**
       * <code>string message_id = 2;</code>
       * @param value The bytes for messageId to set.
       * @return This builder for chaining.
       */
      public Builder setMessageIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        messageId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 3;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 3;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 3;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 3;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object event_ = "";
      /**
       * <code>string event = 4;</code>
       * @return The event.
       */
      public java.lang.String getEvent() {
        java.lang.Object ref = event_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          event_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string event = 4;</code>
       * @return The bytes for event.
       */
      public com.google.protobuf.ByteString
          getEventBytes() {
        java.lang.Object ref = event_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          event_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string event = 4;</code>
       * @param value The event to set.
       * @return This builder for chaining.
       */
      public Builder setEvent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        event_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string event = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearEvent() {
        
        event_ = getDefaultInstance().getEvent();
        onChanged();
        return this;
      }
      /**
       * <code>string event = 4;</code>
       * @param value The bytes for event to set.
       * @return This builder for chaining.
       */
      public Builder setEventBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        event_ = value;
        onChanged();
        return this;
      }

      private long created_ ;
      /**
       * <code>int64 created = 5;</code>
       * @return The created.
       */
      @java.lang.Override
      public long getCreated() {
        return created_;
      }
      /**
       * <code>int64 created = 5;</code>
       * @param value The created to set.
       * @return This builder for chaining.
       */
      public Builder setCreated(long value) {
        
        created_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 created = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearCreated() {
        
        created_ = 0L;
        onChanged();
        return this;
      }

      private int status_ = 0;
      /**
       * <code>.conductor.proto.EventExecution.Status status = 6;</code>
       * @return The enum numeric value on the wire for status.
       */
      @java.lang.Override public int getStatusValue() {
        return status_;
      }
      /**
       * <code>.conductor.proto.EventExecution.Status status = 6;</code>
       * @param value The enum numeric value on the wire for status to set.
       * @return This builder for chaining.
       */
      public Builder setStatusValue(int value) {
        
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.conductor.proto.EventExecution.Status status = 6;</code>
       * @return The status.
       */
      @java.lang.Override
      public com.netflix.conductor.proto.EventExecutionPb.EventExecution.Status getStatus() {
        @SuppressWarnings("deprecation")
        com.netflix.conductor.proto.EventExecutionPb.EventExecution.Status result = com.netflix.conductor.proto.EventExecutionPb.EventExecution.Status.valueOf(status_);
        return result == null ? com.netflix.conductor.proto.EventExecutionPb.EventExecution.Status.UNRECOGNIZED : result;
      }
      /**
       * <code>.conductor.proto.EventExecution.Status status = 6;</code>
       * @param value The status to set.
       * @return This builder for chaining.
       */
      public Builder setStatus(com.netflix.conductor.proto.EventExecutionPb.EventExecution.Status value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        status_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.conductor.proto.EventExecution.Status status = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatus() {
        
        status_ = 0;
        onChanged();
        return this;
      }

      private int action_ = 0;
      /**
       * <code>.conductor.proto.EventHandler.Action.Type action = 7;</code>
       * @return The enum numeric value on the wire for action.
       */
      @java.lang.Override public int getActionValue() {
        return action_;
      }
      /**
       * <code>.conductor.proto.EventHandler.Action.Type action = 7;</code>
       * @param value The enum numeric value on the wire for action to set.
       * @return This builder for chaining.
       */
      public Builder setActionValue(int value) {
        
        action_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.conductor.proto.EventHandler.Action.Type action = 7;</code>
       * @return The action.
       */
      @java.lang.Override
      public com.netflix.conductor.proto.EventHandlerPb.EventHandler.Action.Type getAction() {
        @SuppressWarnings("deprecation")
        com.netflix.conductor.proto.EventHandlerPb.EventHandler.Action.Type result = com.netflix.conductor.proto.EventHandlerPb.EventHandler.Action.Type.valueOf(action_);
        return result == null ? com.netflix.conductor.proto.EventHandlerPb.EventHandler.Action.Type.UNRECOGNIZED : result;
      }
      /**
       * <code>.conductor.proto.EventHandler.Action.Type action = 7;</code>
       * @param value The action to set.
       * @return This builder for chaining.
       */
      public Builder setAction(com.netflix.conductor.proto.EventHandlerPb.EventHandler.Action.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        action_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.conductor.proto.EventHandler.Action.Type action = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearAction() {
        
        action_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, com.google.protobuf.Value> output_;
      private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.Value>
      internalGetOutput() {
        if (output_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              OutputDefaultEntryHolder.defaultEntry);
        }
        return output_;
      }
      private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.Value>
      internalGetMutableOutput() {
        onChanged();;
        if (output_ == null) {
          output_ = com.google.protobuf.MapField.newMapField(
              OutputDefaultEntryHolder.defaultEntry);
        }
        if (!output_.isMutable()) {
          output_ = output_.copy();
        }
        return output_;
      }

      public int getOutputCount() {
        return internalGetOutput().getMap().size();
      }
      /**
       * <code>map&lt;string, .google.protobuf.Value&gt; output = 8;</code>
       */

      @java.lang.Override
      public boolean containsOutput(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetOutput().getMap().containsKey(key);
      }
      /**
       * Use {@link #getOutputMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, com.google.protobuf.Value> getOutput() {
        return getOutputMap();
      }
      /**
       * <code>map&lt;string, .google.protobuf.Value&gt; output = 8;</code>
       */
      @java.lang.Override

      public java.util.Map<java.lang.String, com.google.protobuf.Value> getOutputMap() {
        return internalGetOutput().getMap();
      }
      /**
       * <code>map&lt;string, .google.protobuf.Value&gt; output = 8;</code>
       */
      @java.lang.Override

      public com.google.protobuf.Value getOutputOrDefault(
          java.lang.String key,
          com.google.protobuf.Value defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, com.google.protobuf.Value> map =
            internalGetOutput().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, .google.protobuf.Value&gt; output = 8;</code>
       */
      @java.lang.Override

      public com.google.protobuf.Value getOutputOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, com.google.protobuf.Value> map =
            internalGetOutput().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearOutput() {
        internalGetMutableOutput().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, .google.protobuf.Value&gt; output = 8;</code>
       */

      public Builder removeOutput(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableOutput().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, com.google.protobuf.Value>
      getMutableOutput() {
        return internalGetMutableOutput().getMutableMap();
      }
      /**
       * <code>map&lt;string, .google.protobuf.Value&gt; output = 8;</code>
       */
      public Builder putOutput(
          java.lang.String key,
          com.google.protobuf.Value value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableOutput().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, .google.protobuf.Value&gt; output = 8;</code>
       */

      public Builder putAllOutput(
          java.util.Map<java.lang.String, com.google.protobuf.Value> values) {
        internalGetMutableOutput().getMutableMap()
            .putAll(values);
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:conductor.proto.EventExecution)
    }

    // @@protoc_insertion_point(class_scope:conductor.proto.EventExecution)
    private static final com.netflix.conductor.proto.EventExecutionPb.EventExecution DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.netflix.conductor.proto.EventExecutionPb.EventExecution();
    }

    public static com.netflix.conductor.proto.EventExecutionPb.EventExecution getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EventExecution>
        PARSER = new com.google.protobuf.AbstractParser<EventExecution>() {
      @java.lang.Override
      public EventExecution parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EventExecution(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<EventExecution> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EventExecution> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.netflix.conductor.proto.EventExecutionPb.EventExecution getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_conductor_proto_EventExecution_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_conductor_proto_EventExecution_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_conductor_proto_EventExecution_OutputEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_conductor_proto_EventExecution_OutputEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032model/eventexecution.proto\022\017conductor." +
      "proto\032\030model/eventhandler.proto\032\034google/" +
      "protobuf/struct.proto\"\230\003\n\016EventExecution" +
      "\022\n\n\002id\030\001 \001(\t\022\022\n\nmessage_id\030\002 \001(\t\022\014\n\004name" +
      "\030\003 \001(\t\022\r\n\005event\030\004 \001(\t\022\017\n\007created\030\005 \001(\003\0226" +
      "\n\006status\030\006 \001(\0162&.conductor.proto.EventEx" +
      "ecution.Status\0229\n\006action\030\007 \001(\0162).conduct" +
      "or.proto.EventHandler.Action.Type\022;\n\006out" +
      "put\030\010 \003(\0132+.conductor.proto.EventExecuti" +
      "on.OutputEntry\032E\n\013OutputEntry\022\013\n\003key\030\001 \001" +
      "(\t\022%\n\005value\030\002 \001(\0132\026.google.protobuf.Valu" +
      "e:\0028\001\"A\n\006Status\022\017\n\013IN_PROGRESS\020\000\022\r\n\tCOMP" +
      "LETED\020\001\022\n\n\006FAILED\020\002\022\013\n\007SKIPPED\020\003Bk\n\033com." +
      "netflix.conductor.protoB\020EventExecutionP" +
      "bZ:github.com/netflix/conductor/client/g" +
      "ogrpc/conductor/modelb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.netflix.conductor.proto.EventHandlerPb.getDescriptor(),
          com.google.protobuf.StructProto.getDescriptor(),
        });
    internal_static_conductor_proto_EventExecution_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_conductor_proto_EventExecution_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_conductor_proto_EventExecution_descriptor,
        new java.lang.String[] { "Id", "MessageId", "Name", "Event", "Created", "Status", "Action", "Output", });
    internal_static_conductor_proto_EventExecution_OutputEntry_descriptor =
      internal_static_conductor_proto_EventExecution_descriptor.getNestedTypes().get(0);
    internal_static_conductor_proto_EventExecution_OutputEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_conductor_proto_EventExecution_OutputEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    com.netflix.conductor.proto.EventHandlerPb.getDescriptor();
    com.google.protobuf.StructProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
