// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model/polldata.proto

package com.netflix.conductor.proto;

public final class PollDataPb {
  private PollDataPb() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PollDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:conductor.proto.PollData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string queue_name = 1;</code>
     * @return The queueName.
     */
    java.lang.String getQueueName();
    /**
     * <code>string queue_name = 1;</code>
     * @return The bytes for queueName.
     */
    com.google.protobuf.ByteString
        getQueueNameBytes();

    /**
     * <code>string domain = 2;</code>
     * @return The domain.
     */
    java.lang.String getDomain();
    /**
     * <code>string domain = 2;</code>
     * @return The bytes for domain.
     */
    com.google.protobuf.ByteString
        getDomainBytes();

    /**
     * <code>string worker_id = 3;</code>
     * @return The workerId.
     */
    java.lang.String getWorkerId();
    /**
     * <code>string worker_id = 3;</code>
     * @return The bytes for workerId.
     */
    com.google.protobuf.ByteString
        getWorkerIdBytes();

    /**
     * <code>int64 last_poll_time = 4;</code>
     * @return The lastPollTime.
     */
    long getLastPollTime();
  }
  /**
   * Protobuf type {@code conductor.proto.PollData}
   */
  public static final class PollData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:conductor.proto.PollData)
      PollDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PollData.newBuilder() to construct.
    private PollData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PollData() {
      queueName_ = "";
      domain_ = "";
      workerId_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PollData();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PollData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              queueName_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              domain_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              workerId_ = s;
              break;
            }
            case 32: {

              lastPollTime_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.netflix.conductor.proto.PollDataPb.internal_static_conductor_proto_PollData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.netflix.conductor.proto.PollDataPb.internal_static_conductor_proto_PollData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.netflix.conductor.proto.PollDataPb.PollData.class, com.netflix.conductor.proto.PollDataPb.PollData.Builder.class);
    }

    public static final int QUEUE_NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object queueName_;
    /**
     * <code>string queue_name = 1;</code>
     * @return The queueName.
     */
    @java.lang.Override
    public java.lang.String getQueueName() {
      java.lang.Object ref = queueName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        queueName_ = s;
        return s;
      }
    }
    /**
     * <code>string queue_name = 1;</code>
     * @return The bytes for queueName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getQueueNameBytes() {
      java.lang.Object ref = queueName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        queueName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DOMAIN_FIELD_NUMBER = 2;
    private volatile java.lang.Object domain_;
    /**
     * <code>string domain = 2;</code>
     * @return The domain.
     */
    @java.lang.Override
    public java.lang.String getDomain() {
      java.lang.Object ref = domain_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        domain_ = s;
        return s;
      }
    }
    /**
     * <code>string domain = 2;</code>
     * @return The bytes for domain.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDomainBytes() {
      java.lang.Object ref = domain_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        domain_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int WORKER_ID_FIELD_NUMBER = 3;
    private volatile java.lang.Object workerId_;
    /**
     * <code>string worker_id = 3;</code>
     * @return The workerId.
     */
    @java.lang.Override
    public java.lang.String getWorkerId() {
      java.lang.Object ref = workerId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        workerId_ = s;
        return s;
      }
    }
    /**
     * <code>string worker_id = 3;</code>
     * @return The bytes for workerId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getWorkerIdBytes() {
      java.lang.Object ref = workerId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        workerId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LAST_POLL_TIME_FIELD_NUMBER = 4;
    private long lastPollTime_;
    /**
     * <code>int64 last_poll_time = 4;</code>
     * @return The lastPollTime.
     */
    @java.lang.Override
    public long getLastPollTime() {
      return lastPollTime_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getQueueNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, queueName_);
      }
      if (!getDomainBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, domain_);
      }
      if (!getWorkerIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, workerId_);
      }
      if (lastPollTime_ != 0L) {
        output.writeInt64(4, lastPollTime_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getQueueNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, queueName_);
      }
      if (!getDomainBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, domain_);
      }
      if (!getWorkerIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, workerId_);
      }
      if (lastPollTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, lastPollTime_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.netflix.conductor.proto.PollDataPb.PollData)) {
        return super.equals(obj);
      }
      com.netflix.conductor.proto.PollDataPb.PollData other = (com.netflix.conductor.proto.PollDataPb.PollData) obj;

      if (!getQueueName()
          .equals(other.getQueueName())) return false;
      if (!getDomain()
          .equals(other.getDomain())) return false;
      if (!getWorkerId()
          .equals(other.getWorkerId())) return false;
      if (getLastPollTime()
          != other.getLastPollTime()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + QUEUE_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getQueueName().hashCode();
      hash = (37 * hash) + DOMAIN_FIELD_NUMBER;
      hash = (53 * hash) + getDomain().hashCode();
      hash = (37 * hash) + WORKER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getWorkerId().hashCode();
      hash = (37 * hash) + LAST_POLL_TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLastPollTime());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.netflix.conductor.proto.PollDataPb.PollData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.netflix.conductor.proto.PollDataPb.PollData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.netflix.conductor.proto.PollDataPb.PollData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.netflix.conductor.proto.PollDataPb.PollData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.netflix.conductor.proto.PollDataPb.PollData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.netflix.conductor.proto.PollDataPb.PollData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.netflix.conductor.proto.PollDataPb.PollData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.netflix.conductor.proto.PollDataPb.PollData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.netflix.conductor.proto.PollDataPb.PollData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.netflix.conductor.proto.PollDataPb.PollData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.netflix.conductor.proto.PollDataPb.PollData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.netflix.conductor.proto.PollDataPb.PollData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.netflix.conductor.proto.PollDataPb.PollData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code conductor.proto.PollData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:conductor.proto.PollData)
        com.netflix.conductor.proto.PollDataPb.PollDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.netflix.conductor.proto.PollDataPb.internal_static_conductor_proto_PollData_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.netflix.conductor.proto.PollDataPb.internal_static_conductor_proto_PollData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.netflix.conductor.proto.PollDataPb.PollData.class, com.netflix.conductor.proto.PollDataPb.PollData.Builder.class);
      }

      // Construct using com.netflix.conductor.proto.PollDataPb.PollData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        queueName_ = "";

        domain_ = "";

        workerId_ = "";

        lastPollTime_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.netflix.conductor.proto.PollDataPb.internal_static_conductor_proto_PollData_descriptor;
      }

      @java.lang.Override
      public com.netflix.conductor.proto.PollDataPb.PollData getDefaultInstanceForType() {
        return com.netflix.conductor.proto.PollDataPb.PollData.getDefaultInstance();
      }

      @java.lang.Override
      public com.netflix.conductor.proto.PollDataPb.PollData build() {
        com.netflix.conductor.proto.PollDataPb.PollData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.netflix.conductor.proto.PollDataPb.PollData buildPartial() {
        com.netflix.conductor.proto.PollDataPb.PollData result = new com.netflix.conductor.proto.PollDataPb.PollData(this);
        result.queueName_ = queueName_;
        result.domain_ = domain_;
        result.workerId_ = workerId_;
        result.lastPollTime_ = lastPollTime_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.netflix.conductor.proto.PollDataPb.PollData) {
          return mergeFrom((com.netflix.conductor.proto.PollDataPb.PollData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.netflix.conductor.proto.PollDataPb.PollData other) {
        if (other == com.netflix.conductor.proto.PollDataPb.PollData.getDefaultInstance()) return this;
        if (!other.getQueueName().isEmpty()) {
          queueName_ = other.queueName_;
          onChanged();
        }
        if (!other.getDomain().isEmpty()) {
          domain_ = other.domain_;
          onChanged();
        }
        if (!other.getWorkerId().isEmpty()) {
          workerId_ = other.workerId_;
          onChanged();
        }
        if (other.getLastPollTime() != 0L) {
          setLastPollTime(other.getLastPollTime());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.netflix.conductor.proto.PollDataPb.PollData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.netflix.conductor.proto.PollDataPb.PollData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object queueName_ = "";
      /**
       * <code>string queue_name = 1;</code>
       * @return The queueName.
       */
      public java.lang.String getQueueName() {
        java.lang.Object ref = queueName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          queueName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string queue_name = 1;</code>
       * @return The bytes for queueName.
       */
      public com.google.protobuf.ByteString
          getQueueNameBytes() {
        java.lang.Object ref = queueName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          queueName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string queue_name = 1;</code>
       * @param value The queueName to set.
       * @return This builder for chaining.
       */
      public Builder setQueueName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        queueName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string queue_name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearQueueName() {
        
        queueName_ = getDefaultInstance().getQueueName();
        onChanged();
        return this;
      }
      /**
       * <code>string queue_name = 1;</code>
       * @param value The bytes for queueName to set.
       * @return This builder for chaining.
       */
      public Builder setQueueNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        queueName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object domain_ = "";
      /**
       * <code>string domain = 2;</code>
       * @return The domain.
       */
      public java.lang.String getDomain() {
        java.lang.Object ref = domain_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          domain_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string domain = 2;</code>
       * @return The bytes for domain.
       */
      public com.google.protobuf.ByteString
          getDomainBytes() {
        java.lang.Object ref = domain_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          domain_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string domain = 2;</code>
       * @param value The domain to set.
       * @return This builder for chaining.
       */
      public Builder setDomain(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        domain_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string domain = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearDomain() {
        
        domain_ = getDefaultInstance().getDomain();
        onChanged();
        return this;
      }
      /**
       * <code>string domain = 2;</code>
       * @param value The bytes for domain to set.
       * @return This builder for chaining.
       */
      public Builder setDomainBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        domain_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object workerId_ = "";
      /**
       * <code>string worker_id = 3;</code>
       * @return The workerId.
       */
      public java.lang.String getWorkerId() {
        java.lang.Object ref = workerId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          workerId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string worker_id = 3;</code>
       * @return The bytes for workerId.
       */
      public com.google.protobuf.ByteString
          getWorkerIdBytes() {
        java.lang.Object ref = workerId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          workerId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string worker_id = 3;</code>
       * @param value The workerId to set.
       * @return This builder for chaining.
       */
      public Builder setWorkerId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        workerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string worker_id = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearWorkerId() {
        
        workerId_ = getDefaultInstance().getWorkerId();
        onChanged();
        return this;
      }
      /**
       * <code>string worker_id = 3;</code>
       * @param value The bytes for workerId to set.
       * @return This builder for chaining.
       */
      public Builder setWorkerIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        workerId_ = value;
        onChanged();
        return this;
      }

      private long lastPollTime_ ;
      /**
       * <code>int64 last_poll_time = 4;</code>
       * @return The lastPollTime.
       */
      @java.lang.Override
      public long getLastPollTime() {
        return lastPollTime_;
      }
      /**
       * <code>int64 last_poll_time = 4;</code>
       * @param value The lastPollTime to set.
       * @return This builder for chaining.
       */
      public Builder setLastPollTime(long value) {
        
        lastPollTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 last_poll_time = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearLastPollTime() {
        
        lastPollTime_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:conductor.proto.PollData)
    }

    // @@protoc_insertion_point(class_scope:conductor.proto.PollData)
    private static final com.netflix.conductor.proto.PollDataPb.PollData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.netflix.conductor.proto.PollDataPb.PollData();
    }

    public static com.netflix.conductor.proto.PollDataPb.PollData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PollData>
        PARSER = new com.google.protobuf.AbstractParser<PollData>() {
      @java.lang.Override
      public PollData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PollData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PollData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PollData> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.netflix.conductor.proto.PollDataPb.PollData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_conductor_proto_PollData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_conductor_proto_PollData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024model/polldata.proto\022\017conductor.proto\"" +
      "Y\n\010PollData\022\022\n\nqueue_name\030\001 \001(\t\022\016\n\006domai" +
      "n\030\002 \001(\t\022\021\n\tworker_id\030\003 \001(\t\022\026\n\016last_poll_" +
      "time\030\004 \001(\003Be\n\033com.netflix.conductor.prot" +
      "oB\nPollDataPbZ:github.com/netflix/conduc" +
      "tor/client/gogrpc/conductor/modelb\006proto" +
      "3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_conductor_proto_PollData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_conductor_proto_PollData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_conductor_proto_PollData_descriptor,
        new java.lang.String[] { "QueueName", "Domain", "WorkerId", "LastPollTime", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
