// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model/startworkflowrequest.proto

package com.netflix.conductor.proto;

public final class StartWorkflowRequestPb {
  private StartWorkflowRequestPb() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface StartWorkflowRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:conductor.proto.StartWorkflowRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>int32 version = 2;</code>
     * @return The version.
     */
    int getVersion();

    /**
     * <code>string correlation_id = 3;</code>
     * @return The correlationId.
     */
    java.lang.String getCorrelationId();
    /**
     * <code>string correlation_id = 3;</code>
     * @return The bytes for correlationId.
     */
    com.google.protobuf.ByteString
        getCorrelationIdBytes();

    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; input = 4;</code>
     */
    int getInputCount();
    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; input = 4;</code>
     */
    boolean containsInput(
        java.lang.String key);
    /**
     * Use {@link #getInputMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, com.google.protobuf.Value>
    getInput();
    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; input = 4;</code>
     */
    java.util.Map<java.lang.String, com.google.protobuf.Value>
    getInputMap();
    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; input = 4;</code>
     */

    com.google.protobuf.Value getInputOrDefault(
        java.lang.String key,
        com.google.protobuf.Value defaultValue);
    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; input = 4;</code>
     */

    com.google.protobuf.Value getInputOrThrow(
        java.lang.String key);

    /**
     * <code>map&lt;string, string&gt; task_to_domain = 5;</code>
     */
    int getTaskToDomainCount();
    /**
     * <code>map&lt;string, string&gt; task_to_domain = 5;</code>
     */
    boolean containsTaskToDomain(
        java.lang.String key);
    /**
     * Use {@link #getTaskToDomainMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getTaskToDomain();
    /**
     * <code>map&lt;string, string&gt; task_to_domain = 5;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getTaskToDomainMap();
    /**
     * <code>map&lt;string, string&gt; task_to_domain = 5;</code>
     */

    java.lang.String getTaskToDomainOrDefault(
        java.lang.String key,
        java.lang.String defaultValue);
    /**
     * <code>map&lt;string, string&gt; task_to_domain = 5;</code>
     */

    java.lang.String getTaskToDomainOrThrow(
        java.lang.String key);

    /**
     * <code>.conductor.proto.WorkflowDef workflow_def = 6;</code>
     * @return Whether the workflowDef field is set.
     */
    boolean hasWorkflowDef();
    /**
     * <code>.conductor.proto.WorkflowDef workflow_def = 6;</code>
     * @return The workflowDef.
     */
    com.netflix.conductor.proto.WorkflowDefPb.WorkflowDef getWorkflowDef();
    /**
     * <code>.conductor.proto.WorkflowDef workflow_def = 6;</code>
     */
    com.netflix.conductor.proto.WorkflowDefPb.WorkflowDefOrBuilder getWorkflowDefOrBuilder();

    /**
     * <code>string external_input_payload_storage_path = 7;</code>
     * @return The externalInputPayloadStoragePath.
     */
    java.lang.String getExternalInputPayloadStoragePath();
    /**
     * <code>string external_input_payload_storage_path = 7;</code>
     * @return The bytes for externalInputPayloadStoragePath.
     */
    com.google.protobuf.ByteString
        getExternalInputPayloadStoragePathBytes();

    /**
     * <code>int32 priority = 8;</code>
     * @return The priority.
     */
    int getPriority();
  }
  /**
   * Protobuf type {@code conductor.proto.StartWorkflowRequest}
   */
  public static final class StartWorkflowRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:conductor.proto.StartWorkflowRequest)
      StartWorkflowRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use StartWorkflowRequest.newBuilder() to construct.
    private StartWorkflowRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private StartWorkflowRequest() {
      name_ = "";
      correlationId_ = "";
      externalInputPayloadStoragePath_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new StartWorkflowRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private StartWorkflowRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 16: {

              version_ = input.readInt32();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              correlationId_ = s;
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                input_ = com.google.protobuf.MapField.newMapField(
                    InputDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<java.lang.String, com.google.protobuf.Value>
              input__ = input.readMessage(
                  InputDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              input_.getMutableMap().put(
                  input__.getKey(), input__.getValue());
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                taskToDomain_ = com.google.protobuf.MapField.newMapField(
                    TaskToDomainDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000002;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              taskToDomain__ = input.readMessage(
                  TaskToDomainDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              taskToDomain_.getMutableMap().put(
                  taskToDomain__.getKey(), taskToDomain__.getValue());
              break;
            }
            case 50: {
              com.netflix.conductor.proto.WorkflowDefPb.WorkflowDef.Builder subBuilder = null;
              if (workflowDef_ != null) {
                subBuilder = workflowDef_.toBuilder();
              }
              workflowDef_ = input.readMessage(com.netflix.conductor.proto.WorkflowDefPb.WorkflowDef.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(workflowDef_);
                workflowDef_ = subBuilder.buildPartial();
              }

              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              externalInputPayloadStoragePath_ = s;
              break;
            }
            case 64: {

              priority_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.netflix.conductor.proto.StartWorkflowRequestPb.internal_static_conductor_proto_StartWorkflowRequest_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 4:
          return internalGetInput();
        case 5:
          return internalGetTaskToDomain();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.netflix.conductor.proto.StartWorkflowRequestPb.internal_static_conductor_proto_StartWorkflowRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.netflix.conductor.proto.StartWorkflowRequestPb.StartWorkflowRequest.class, com.netflix.conductor.proto.StartWorkflowRequestPb.StartWorkflowRequest.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VERSION_FIELD_NUMBER = 2;
    private int version_;
    /**
     * <code>int32 version = 2;</code>
     * @return The version.
     */
    @java.lang.Override
    public int getVersion() {
      return version_;
    }

    public static final int CORRELATION_ID_FIELD_NUMBER = 3;
    private volatile java.lang.Object correlationId_;
    /**
     * <code>string correlation_id = 3;</code>
     * @return The correlationId.
     */
    @java.lang.Override
    public java.lang.String getCorrelationId() {
      java.lang.Object ref = correlationId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        correlationId_ = s;
        return s;
      }
    }
    /**
     * <code>string correlation_id = 3;</code>
     * @return The bytes for correlationId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCorrelationIdBytes() {
      java.lang.Object ref = correlationId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        correlationId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INPUT_FIELD_NUMBER = 4;
    private static final class InputDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, com.google.protobuf.Value> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, com.google.protobuf.Value>newDefaultInstance(
                  com.netflix.conductor.proto.StartWorkflowRequestPb.internal_static_conductor_proto_StartWorkflowRequest_InputEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  com.google.protobuf.Value.getDefaultInstance());
    }
    private com.google.protobuf.MapField<
        java.lang.String, com.google.protobuf.Value> input_;
    private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.Value>
    internalGetInput() {
      if (input_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            InputDefaultEntryHolder.defaultEntry);
      }
      return input_;
    }

    public int getInputCount() {
      return internalGetInput().getMap().size();
    }
    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; input = 4;</code>
     */

    @java.lang.Override
    public boolean containsInput(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetInput().getMap().containsKey(key);
    }
    /**
     * Use {@link #getInputMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.google.protobuf.Value> getInput() {
      return getInputMap();
    }
    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; input = 4;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, com.google.protobuf.Value> getInputMap() {
      return internalGetInput().getMap();
    }
    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; input = 4;</code>
     */
    @java.lang.Override

    public com.google.protobuf.Value getInputOrDefault(
        java.lang.String key,
        com.google.protobuf.Value defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.google.protobuf.Value> map =
          internalGetInput().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; input = 4;</code>
     */
    @java.lang.Override

    public com.google.protobuf.Value getInputOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.google.protobuf.Value> map =
          internalGetInput().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public static final int TASK_TO_DOMAIN_FIELD_NUMBER = 5;
    private static final class TaskToDomainDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  com.netflix.conductor.proto.StartWorkflowRequestPb.internal_static_conductor_proto_StartWorkflowRequest_TaskToDomainEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> taskToDomain_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetTaskToDomain() {
      if (taskToDomain_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            TaskToDomainDefaultEntryHolder.defaultEntry);
      }
      return taskToDomain_;
    }

    public int getTaskToDomainCount() {
      return internalGetTaskToDomain().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; task_to_domain = 5;</code>
     */

    @java.lang.Override
    public boolean containsTaskToDomain(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetTaskToDomain().getMap().containsKey(key);
    }
    /**
     * Use {@link #getTaskToDomainMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getTaskToDomain() {
      return getTaskToDomainMap();
    }
    /**
     * <code>map&lt;string, string&gt; task_to_domain = 5;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, java.lang.String> getTaskToDomainMap() {
      return internalGetTaskToDomain().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; task_to_domain = 5;</code>
     */
    @java.lang.Override

    public java.lang.String getTaskToDomainOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetTaskToDomain().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; task_to_domain = 5;</code>
     */
    @java.lang.Override

    public java.lang.String getTaskToDomainOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetTaskToDomain().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public static final int WORKFLOW_DEF_FIELD_NUMBER = 6;
    private com.netflix.conductor.proto.WorkflowDefPb.WorkflowDef workflowDef_;
    /**
     * <code>.conductor.proto.WorkflowDef workflow_def = 6;</code>
     * @return Whether the workflowDef field is set.
     */
    @java.lang.Override
    public boolean hasWorkflowDef() {
      return workflowDef_ != null;
    }
    /**
     * <code>.conductor.proto.WorkflowDef workflow_def = 6;</code>
     * @return The workflowDef.
     */
    @java.lang.Override
    public com.netflix.conductor.proto.WorkflowDefPb.WorkflowDef getWorkflowDef() {
      return workflowDef_ == null ? com.netflix.conductor.proto.WorkflowDefPb.WorkflowDef.getDefaultInstance() : workflowDef_;
    }
    /**
     * <code>.conductor.proto.WorkflowDef workflow_def = 6;</code>
     */
    @java.lang.Override
    public com.netflix.conductor.proto.WorkflowDefPb.WorkflowDefOrBuilder getWorkflowDefOrBuilder() {
      return getWorkflowDef();
    }

    public static final int EXTERNAL_INPUT_PAYLOAD_STORAGE_PATH_FIELD_NUMBER = 7;
    private volatile java.lang.Object externalInputPayloadStoragePath_;
    /**
     * <code>string external_input_payload_storage_path = 7;</code>
     * @return The externalInputPayloadStoragePath.
     */
    @java.lang.Override
    public java.lang.String getExternalInputPayloadStoragePath() {
      java.lang.Object ref = externalInputPayloadStoragePath_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        externalInputPayloadStoragePath_ = s;
        return s;
      }
    }
    /**
     * <code>string external_input_payload_storage_path = 7;</code>
     * @return The bytes for externalInputPayloadStoragePath.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getExternalInputPayloadStoragePathBytes() {
      java.lang.Object ref = externalInputPayloadStoragePath_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        externalInputPayloadStoragePath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PRIORITY_FIELD_NUMBER = 8;
    private int priority_;
    /**
     * <code>int32 priority = 8;</code>
     * @return The priority.
     */
    @java.lang.Override
    public int getPriority() {
      return priority_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (version_ != 0) {
        output.writeInt32(2, version_);
      }
      if (!getCorrelationIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, correlationId_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetInput(),
          InputDefaultEntryHolder.defaultEntry,
          4);
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetTaskToDomain(),
          TaskToDomainDefaultEntryHolder.defaultEntry,
          5);
      if (workflowDef_ != null) {
        output.writeMessage(6, getWorkflowDef());
      }
      if (!getExternalInputPayloadStoragePathBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, externalInputPayloadStoragePath_);
      }
      if (priority_ != 0) {
        output.writeInt32(8, priority_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (version_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, version_);
      }
      if (!getCorrelationIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, correlationId_);
      }
      for (java.util.Map.Entry<java.lang.String, com.google.protobuf.Value> entry
           : internalGetInput().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, com.google.protobuf.Value>
        input__ = InputDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(4, input__);
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetTaskToDomain().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        taskToDomain__ = TaskToDomainDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(5, taskToDomain__);
      }
      if (workflowDef_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, getWorkflowDef());
      }
      if (!getExternalInputPayloadStoragePathBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, externalInputPayloadStoragePath_);
      }
      if (priority_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, priority_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.netflix.conductor.proto.StartWorkflowRequestPb.StartWorkflowRequest)) {
        return super.equals(obj);
      }
      com.netflix.conductor.proto.StartWorkflowRequestPb.StartWorkflowRequest other = (com.netflix.conductor.proto.StartWorkflowRequestPb.StartWorkflowRequest) obj;

      if (!getName()
          .equals(other.getName())) return false;
      if (getVersion()
          != other.getVersion()) return false;
      if (!getCorrelationId()
          .equals(other.getCorrelationId())) return false;
      if (!internalGetInput().equals(
          other.internalGetInput())) return false;
      if (!internalGetTaskToDomain().equals(
          other.internalGetTaskToDomain())) return false;
      if (hasWorkflowDef() != other.hasWorkflowDef()) return false;
      if (hasWorkflowDef()) {
        if (!getWorkflowDef()
            .equals(other.getWorkflowDef())) return false;
      }
      if (!getExternalInputPayloadStoragePath()
          .equals(other.getExternalInputPayloadStoragePath())) return false;
      if (getPriority()
          != other.getPriority()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion();
      hash = (37 * hash) + CORRELATION_ID_FIELD_NUMBER;
      hash = (53 * hash) + getCorrelationId().hashCode();
      if (!internalGetInput().getMap().isEmpty()) {
        hash = (37 * hash) + INPUT_FIELD_NUMBER;
        hash = (53 * hash) + internalGetInput().hashCode();
      }
      if (!internalGetTaskToDomain().getMap().isEmpty()) {
        hash = (37 * hash) + TASK_TO_DOMAIN_FIELD_NUMBER;
        hash = (53 * hash) + internalGetTaskToDomain().hashCode();
      }
      if (hasWorkflowDef()) {
        hash = (37 * hash) + WORKFLOW_DEF_FIELD_NUMBER;
        hash = (53 * hash) + getWorkflowDef().hashCode();
      }
      hash = (37 * hash) + EXTERNAL_INPUT_PAYLOAD_STORAGE_PATH_FIELD_NUMBER;
      hash = (53 * hash) + getExternalInputPayloadStoragePath().hashCode();
      hash = (37 * hash) + PRIORITY_FIELD_NUMBER;
      hash = (53 * hash) + getPriority();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.netflix.conductor.proto.StartWorkflowRequestPb.StartWorkflowRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.netflix.conductor.proto.StartWorkflowRequestPb.StartWorkflowRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.netflix.conductor.proto.StartWorkflowRequestPb.StartWorkflowRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.netflix.conductor.proto.StartWorkflowRequestPb.StartWorkflowRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.netflix.conductor.proto.StartWorkflowRequestPb.StartWorkflowRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.netflix.conductor.proto.StartWorkflowRequestPb.StartWorkflowRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.netflix.conductor.proto.StartWorkflowRequestPb.StartWorkflowRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.netflix.conductor.proto.StartWorkflowRequestPb.StartWorkflowRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.netflix.conductor.proto.StartWorkflowRequestPb.StartWorkflowRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.netflix.conductor.proto.StartWorkflowRequestPb.StartWorkflowRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.netflix.conductor.proto.StartWorkflowRequestPb.StartWorkflowRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.netflix.conductor.proto.StartWorkflowRequestPb.StartWorkflowRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.netflix.conductor.proto.StartWorkflowRequestPb.StartWorkflowRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code conductor.proto.StartWorkflowRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:conductor.proto.StartWorkflowRequest)
        com.netflix.conductor.proto.StartWorkflowRequestPb.StartWorkflowRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.netflix.conductor.proto.StartWorkflowRequestPb.internal_static_conductor_proto_StartWorkflowRequest_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 4:
            return internalGetInput();
          case 5:
            return internalGetTaskToDomain();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 4:
            return internalGetMutableInput();
          case 5:
            return internalGetMutableTaskToDomain();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.netflix.conductor.proto.StartWorkflowRequestPb.internal_static_conductor_proto_StartWorkflowRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.netflix.conductor.proto.StartWorkflowRequestPb.StartWorkflowRequest.class, com.netflix.conductor.proto.StartWorkflowRequestPb.StartWorkflowRequest.Builder.class);
      }

      // Construct using com.netflix.conductor.proto.StartWorkflowRequestPb.StartWorkflowRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        name_ = "";

        version_ = 0;

        correlationId_ = "";

        internalGetMutableInput().clear();
        internalGetMutableTaskToDomain().clear();
        if (workflowDefBuilder_ == null) {
          workflowDef_ = null;
        } else {
          workflowDef_ = null;
          workflowDefBuilder_ = null;
        }
        externalInputPayloadStoragePath_ = "";

        priority_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.netflix.conductor.proto.StartWorkflowRequestPb.internal_static_conductor_proto_StartWorkflowRequest_descriptor;
      }

      @java.lang.Override
      public com.netflix.conductor.proto.StartWorkflowRequestPb.StartWorkflowRequest getDefaultInstanceForType() {
        return com.netflix.conductor.proto.StartWorkflowRequestPb.StartWorkflowRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.netflix.conductor.proto.StartWorkflowRequestPb.StartWorkflowRequest build() {
        com.netflix.conductor.proto.StartWorkflowRequestPb.StartWorkflowRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.netflix.conductor.proto.StartWorkflowRequestPb.StartWorkflowRequest buildPartial() {
        com.netflix.conductor.proto.StartWorkflowRequestPb.StartWorkflowRequest result = new com.netflix.conductor.proto.StartWorkflowRequestPb.StartWorkflowRequest(this);
        int from_bitField0_ = bitField0_;
        result.name_ = name_;
        result.version_ = version_;
        result.correlationId_ = correlationId_;
        result.input_ = internalGetInput();
        result.input_.makeImmutable();
        result.taskToDomain_ = internalGetTaskToDomain();
        result.taskToDomain_.makeImmutable();
        if (workflowDefBuilder_ == null) {
          result.workflowDef_ = workflowDef_;
        } else {
          result.workflowDef_ = workflowDefBuilder_.build();
        }
        result.externalInputPayloadStoragePath_ = externalInputPayloadStoragePath_;
        result.priority_ = priority_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.netflix.conductor.proto.StartWorkflowRequestPb.StartWorkflowRequest) {
          return mergeFrom((com.netflix.conductor.proto.StartWorkflowRequestPb.StartWorkflowRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.netflix.conductor.proto.StartWorkflowRequestPb.StartWorkflowRequest other) {
        if (other == com.netflix.conductor.proto.StartWorkflowRequestPb.StartWorkflowRequest.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getVersion() != 0) {
          setVersion(other.getVersion());
        }
        if (!other.getCorrelationId().isEmpty()) {
          correlationId_ = other.correlationId_;
          onChanged();
        }
        internalGetMutableInput().mergeFrom(
            other.internalGetInput());
        internalGetMutableTaskToDomain().mergeFrom(
            other.internalGetTaskToDomain());
        if (other.hasWorkflowDef()) {
          mergeWorkflowDef(other.getWorkflowDef());
        }
        if (!other.getExternalInputPayloadStoragePath().isEmpty()) {
          externalInputPayloadStoragePath_ = other.externalInputPayloadStoragePath_;
          onChanged();
        }
        if (other.getPriority() != 0) {
          setPriority(other.getPriority());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.netflix.conductor.proto.StartWorkflowRequestPb.StartWorkflowRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.netflix.conductor.proto.StartWorkflowRequestPb.StartWorkflowRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private int version_ ;
      /**
       * <code>int32 version = 2;</code>
       * @return The version.
       */
      @java.lang.Override
      public int getVersion() {
        return version_;
      }
      /**
       * <code>int32 version = 2;</code>
       * @param value The version to set.
       * @return This builder for chaining.
       */
      public Builder setVersion(int value) {
        
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 version = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearVersion() {
        
        version_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object correlationId_ = "";
      /**
       * <code>string correlation_id = 3;</code>
       * @return The correlationId.
       */
      public java.lang.String getCorrelationId() {
        java.lang.Object ref = correlationId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          correlationId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string correlation_id = 3;</code>
       * @return The bytes for correlationId.
       */
      public com.google.protobuf.ByteString
          getCorrelationIdBytes() {
        java.lang.Object ref = correlationId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          correlationId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string correlation_id = 3;</code>
       * @param value The correlationId to set.
       * @return This builder for chaining.
       */
      public Builder setCorrelationId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        correlationId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string correlation_id = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearCorrelationId() {
        
        correlationId_ = getDefaultInstance().getCorrelationId();
        onChanged();
        return this;
      }
      /**
       * <code>string correlation_id = 3;</code>
       * @param value The bytes for correlationId to set.
       * @return This builder for chaining.
       */
      public Builder setCorrelationIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        correlationId_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, com.google.protobuf.Value> input_;
      private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.Value>
      internalGetInput() {
        if (input_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              InputDefaultEntryHolder.defaultEntry);
        }
        return input_;
      }
      private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.Value>
      internalGetMutableInput() {
        onChanged();;
        if (input_ == null) {
          input_ = com.google.protobuf.MapField.newMapField(
              InputDefaultEntryHolder.defaultEntry);
        }
        if (!input_.isMutable()) {
          input_ = input_.copy();
        }
        return input_;
      }

      public int getInputCount() {
        return internalGetInput().getMap().size();
      }
      /**
       * <code>map&lt;string, .google.protobuf.Value&gt; input = 4;</code>
       */

      @java.lang.Override
      public boolean containsInput(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetInput().getMap().containsKey(key);
      }
      /**
       * Use {@link #getInputMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, com.google.protobuf.Value> getInput() {
        return getInputMap();
      }
      /**
       * <code>map&lt;string, .google.protobuf.Value&gt; input = 4;</code>
       */
      @java.lang.Override

      public java.util.Map<java.lang.String, com.google.protobuf.Value> getInputMap() {
        return internalGetInput().getMap();
      }
      /**
       * <code>map&lt;string, .google.protobuf.Value&gt; input = 4;</code>
       */
      @java.lang.Override

      public com.google.protobuf.Value getInputOrDefault(
          java.lang.String key,
          com.google.protobuf.Value defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, com.google.protobuf.Value> map =
            internalGetInput().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, .google.protobuf.Value&gt; input = 4;</code>
       */
      @java.lang.Override

      public com.google.protobuf.Value getInputOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, com.google.protobuf.Value> map =
            internalGetInput().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearInput() {
        internalGetMutableInput().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, .google.protobuf.Value&gt; input = 4;</code>
       */

      public Builder removeInput(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableInput().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, com.google.protobuf.Value>
      getMutableInput() {
        return internalGetMutableInput().getMutableMap();
      }
      /**
       * <code>map&lt;string, .google.protobuf.Value&gt; input = 4;</code>
       */
      public Builder putInput(
          java.lang.String key,
          com.google.protobuf.Value value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableInput().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, .google.protobuf.Value&gt; input = 4;</code>
       */

      public Builder putAllInput(
          java.util.Map<java.lang.String, com.google.protobuf.Value> values) {
        internalGetMutableInput().getMutableMap()
            .putAll(values);
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> taskToDomain_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetTaskToDomain() {
        if (taskToDomain_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              TaskToDomainDefaultEntryHolder.defaultEntry);
        }
        return taskToDomain_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMutableTaskToDomain() {
        onChanged();;
        if (taskToDomain_ == null) {
          taskToDomain_ = com.google.protobuf.MapField.newMapField(
              TaskToDomainDefaultEntryHolder.defaultEntry);
        }
        if (!taskToDomain_.isMutable()) {
          taskToDomain_ = taskToDomain_.copy();
        }
        return taskToDomain_;
      }

      public int getTaskToDomainCount() {
        return internalGetTaskToDomain().getMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; task_to_domain = 5;</code>
       */

      @java.lang.Override
      public boolean containsTaskToDomain(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetTaskToDomain().getMap().containsKey(key);
      }
      /**
       * Use {@link #getTaskToDomainMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getTaskToDomain() {
        return getTaskToDomainMap();
      }
      /**
       * <code>map&lt;string, string&gt; task_to_domain = 5;</code>
       */
      @java.lang.Override

      public java.util.Map<java.lang.String, java.lang.String> getTaskToDomainMap() {
        return internalGetTaskToDomain().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; task_to_domain = 5;</code>
       */
      @java.lang.Override

      public java.lang.String getTaskToDomainOrDefault(
          java.lang.String key,
          java.lang.String defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetTaskToDomain().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; task_to_domain = 5;</code>
       */
      @java.lang.Override

      public java.lang.String getTaskToDomainOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetTaskToDomain().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearTaskToDomain() {
        internalGetMutableTaskToDomain().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; task_to_domain = 5;</code>
       */

      public Builder removeTaskToDomain(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableTaskToDomain().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
      getMutableTaskToDomain() {
        return internalGetMutableTaskToDomain().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; task_to_domain = 5;</code>
       */
      public Builder putTaskToDomain(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableTaskToDomain().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; task_to_domain = 5;</code>
       */

      public Builder putAllTaskToDomain(
          java.util.Map<java.lang.String, java.lang.String> values) {
        internalGetMutableTaskToDomain().getMutableMap()
            .putAll(values);
        return this;
      }

      private com.netflix.conductor.proto.WorkflowDefPb.WorkflowDef workflowDef_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.netflix.conductor.proto.WorkflowDefPb.WorkflowDef, com.netflix.conductor.proto.WorkflowDefPb.WorkflowDef.Builder, com.netflix.conductor.proto.WorkflowDefPb.WorkflowDefOrBuilder> workflowDefBuilder_;
      /**
       * <code>.conductor.proto.WorkflowDef workflow_def = 6;</code>
       * @return Whether the workflowDef field is set.
       */
      public boolean hasWorkflowDef() {
        return workflowDefBuilder_ != null || workflowDef_ != null;
      }
      /**
       * <code>.conductor.proto.WorkflowDef workflow_def = 6;</code>
       * @return The workflowDef.
       */
      public com.netflix.conductor.proto.WorkflowDefPb.WorkflowDef getWorkflowDef() {
        if (workflowDefBuilder_ == null) {
          return workflowDef_ == null ? com.netflix.conductor.proto.WorkflowDefPb.WorkflowDef.getDefaultInstance() : workflowDef_;
        } else {
          return workflowDefBuilder_.getMessage();
        }
      }
      /**
       * <code>.conductor.proto.WorkflowDef workflow_def = 6;</code>
       */
      public Builder setWorkflowDef(com.netflix.conductor.proto.WorkflowDefPb.WorkflowDef value) {
        if (workflowDefBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          workflowDef_ = value;
          onChanged();
        } else {
          workflowDefBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.conductor.proto.WorkflowDef workflow_def = 6;</code>
       */
      public Builder setWorkflowDef(
          com.netflix.conductor.proto.WorkflowDefPb.WorkflowDef.Builder builderForValue) {
        if (workflowDefBuilder_ == null) {
          workflowDef_ = builderForValue.build();
          onChanged();
        } else {
          workflowDefBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.conductor.proto.WorkflowDef workflow_def = 6;</code>
       */
      public Builder mergeWorkflowDef(com.netflix.conductor.proto.WorkflowDefPb.WorkflowDef value) {
        if (workflowDefBuilder_ == null) {
          if (workflowDef_ != null) {
            workflowDef_ =
              com.netflix.conductor.proto.WorkflowDefPb.WorkflowDef.newBuilder(workflowDef_).mergeFrom(value).buildPartial();
          } else {
            workflowDef_ = value;
          }
          onChanged();
        } else {
          workflowDefBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.conductor.proto.WorkflowDef workflow_def = 6;</code>
       */
      public Builder clearWorkflowDef() {
        if (workflowDefBuilder_ == null) {
          workflowDef_ = null;
          onChanged();
        } else {
          workflowDef_ = null;
          workflowDefBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.conductor.proto.WorkflowDef workflow_def = 6;</code>
       */
      public com.netflix.conductor.proto.WorkflowDefPb.WorkflowDef.Builder getWorkflowDefBuilder() {
        
        onChanged();
        return getWorkflowDefFieldBuilder().getBuilder();
      }
      /**
       * <code>.conductor.proto.WorkflowDef workflow_def = 6;</code>
       */
      public com.netflix.conductor.proto.WorkflowDefPb.WorkflowDefOrBuilder getWorkflowDefOrBuilder() {
        if (workflowDefBuilder_ != null) {
          return workflowDefBuilder_.getMessageOrBuilder();
        } else {
          return workflowDef_ == null ?
              com.netflix.conductor.proto.WorkflowDefPb.WorkflowDef.getDefaultInstance() : workflowDef_;
        }
      }
      /**
       * <code>.conductor.proto.WorkflowDef workflow_def = 6;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.netflix.conductor.proto.WorkflowDefPb.WorkflowDef, com.netflix.conductor.proto.WorkflowDefPb.WorkflowDef.Builder, com.netflix.conductor.proto.WorkflowDefPb.WorkflowDefOrBuilder> 
          getWorkflowDefFieldBuilder() {
        if (workflowDefBuilder_ == null) {
          workflowDefBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.netflix.conductor.proto.WorkflowDefPb.WorkflowDef, com.netflix.conductor.proto.WorkflowDefPb.WorkflowDef.Builder, com.netflix.conductor.proto.WorkflowDefPb.WorkflowDefOrBuilder>(
                  getWorkflowDef(),
                  getParentForChildren(),
                  isClean());
          workflowDef_ = null;
        }
        return workflowDefBuilder_;
      }

      private java.lang.Object externalInputPayloadStoragePath_ = "";
      /**
       * <code>string external_input_payload_storage_path = 7;</code>
       * @return The externalInputPayloadStoragePath.
       */
      public java.lang.String getExternalInputPayloadStoragePath() {
        java.lang.Object ref = externalInputPayloadStoragePath_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          externalInputPayloadStoragePath_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string external_input_payload_storage_path = 7;</code>
       * @return The bytes for externalInputPayloadStoragePath.
       */
      public com.google.protobuf.ByteString
          getExternalInputPayloadStoragePathBytes() {
        java.lang.Object ref = externalInputPayloadStoragePath_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          externalInputPayloadStoragePath_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string external_input_payload_storage_path = 7;</code>
       * @param value The externalInputPayloadStoragePath to set.
       * @return This builder for chaining.
       */
      public Builder setExternalInputPayloadStoragePath(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        externalInputPayloadStoragePath_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string external_input_payload_storage_path = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearExternalInputPayloadStoragePath() {
        
        externalInputPayloadStoragePath_ = getDefaultInstance().getExternalInputPayloadStoragePath();
        onChanged();
        return this;
      }
      /**
       * <code>string external_input_payload_storage_path = 7;</code>
       * @param value The bytes for externalInputPayloadStoragePath to set.
       * @return This builder for chaining.
       */
      public Builder setExternalInputPayloadStoragePathBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        externalInputPayloadStoragePath_ = value;
        onChanged();
        return this;
      }

      private int priority_ ;
      /**
       * <code>int32 priority = 8;</code>
       * @return The priority.
       */
      @java.lang.Override
      public int getPriority() {
        return priority_;
      }
      /**
       * <code>int32 priority = 8;</code>
       * @param value The priority to set.
       * @return This builder for chaining.
       */
      public Builder setPriority(int value) {
        
        priority_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 priority = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearPriority() {
        
        priority_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:conductor.proto.StartWorkflowRequest)
    }

    // @@protoc_insertion_point(class_scope:conductor.proto.StartWorkflowRequest)
    private static final com.netflix.conductor.proto.StartWorkflowRequestPb.StartWorkflowRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.netflix.conductor.proto.StartWorkflowRequestPb.StartWorkflowRequest();
    }

    public static com.netflix.conductor.proto.StartWorkflowRequestPb.StartWorkflowRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<StartWorkflowRequest>
        PARSER = new com.google.protobuf.AbstractParser<StartWorkflowRequest>() {
      @java.lang.Override
      public StartWorkflowRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new StartWorkflowRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<StartWorkflowRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<StartWorkflowRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.netflix.conductor.proto.StartWorkflowRequestPb.StartWorkflowRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_conductor_proto_StartWorkflowRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_conductor_proto_StartWorkflowRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_conductor_proto_StartWorkflowRequest_InputEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_conductor_proto_StartWorkflowRequest_InputEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_conductor_proto_StartWorkflowRequest_TaskToDomainEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_conductor_proto_StartWorkflowRequest_TaskToDomainEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n model/startworkflowrequest.proto\022\017cond" +
      "uctor.proto\032\027model/workflowdef.proto\032\034go" +
      "ogle/protobuf/struct.proto\"\315\003\n\024StartWork" +
      "flowRequest\022\014\n\004name\030\001 \001(\t\022\017\n\007version\030\002 \001" +
      "(\005\022\026\n\016correlation_id\030\003 \001(\t\022?\n\005input\030\004 \003(" +
      "\01320.conductor.proto.StartWorkflowRequest" +
      ".InputEntry\022O\n\016task_to_domain\030\005 \003(\01327.co" +
      "nductor.proto.StartWorkflowRequest.TaskT" +
      "oDomainEntry\0222\n\014workflow_def\030\006 \001(\0132\034.con" +
      "ductor.proto.WorkflowDef\022+\n#external_inp" +
      "ut_payload_storage_path\030\007 \001(\t\022\020\n\010priorit" +
      "y\030\010 \001(\005\032D\n\nInputEntry\022\013\n\003key\030\001 \001(\t\022%\n\005va" +
      "lue\030\002 \001(\0132\026.google.protobuf.Value:\0028\001\0323\n" +
      "\021TaskToDomainEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value" +
      "\030\002 \001(\t:\0028\001Bq\n\033com.netflix.conductor.prot" +
      "oB\026StartWorkflowRequestPbZ:github.com/ne" +
      "tflix/conductor/client/gogrpc/conductor/" +
      "modelb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.netflix.conductor.proto.WorkflowDefPb.getDescriptor(),
          com.google.protobuf.StructProto.getDescriptor(),
        });
    internal_static_conductor_proto_StartWorkflowRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_conductor_proto_StartWorkflowRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_conductor_proto_StartWorkflowRequest_descriptor,
        new java.lang.String[] { "Name", "Version", "CorrelationId", "Input", "TaskToDomain", "WorkflowDef", "ExternalInputPayloadStoragePath", "Priority", });
    internal_static_conductor_proto_StartWorkflowRequest_InputEntry_descriptor =
      internal_static_conductor_proto_StartWorkflowRequest_descriptor.getNestedTypes().get(0);
    internal_static_conductor_proto_StartWorkflowRequest_InputEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_conductor_proto_StartWorkflowRequest_InputEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_conductor_proto_StartWorkflowRequest_TaskToDomainEntry_descriptor =
      internal_static_conductor_proto_StartWorkflowRequest_descriptor.getNestedTypes().get(1);
    internal_static_conductor_proto_StartWorkflowRequest_TaskToDomainEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_conductor_proto_StartWorkflowRequest_TaskToDomainEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    com.netflix.conductor.proto.WorkflowDefPb.getDescriptor();
    com.google.protobuf.StructProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
