// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model/taskresult.proto

package com.netflix.conductor.proto;

public final class TaskResultPb {
  private TaskResultPb() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TaskResultOrBuilder extends
      // @@protoc_insertion_point(interface_extends:conductor.proto.TaskResult)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string workflow_instance_id = 1;</code>
     * @return The workflowInstanceId.
     */
    java.lang.String getWorkflowInstanceId();
    /**
     * <code>string workflow_instance_id = 1;</code>
     * @return The bytes for workflowInstanceId.
     */
    com.google.protobuf.ByteString
        getWorkflowInstanceIdBytes();

    /**
     * <code>string task_id = 2;</code>
     * @return The taskId.
     */
    java.lang.String getTaskId();
    /**
     * <code>string task_id = 2;</code>
     * @return The bytes for taskId.
     */
    com.google.protobuf.ByteString
        getTaskIdBytes();

    /**
     * <code>string reason_for_incompletion = 3;</code>
     * @return The reasonForIncompletion.
     */
    java.lang.String getReasonForIncompletion();
    /**
     * <code>string reason_for_incompletion = 3;</code>
     * @return The bytes for reasonForIncompletion.
     */
    com.google.protobuf.ByteString
        getReasonForIncompletionBytes();

    /**
     * <code>int64 callback_after_seconds = 4;</code>
     * @return The callbackAfterSeconds.
     */
    long getCallbackAfterSeconds();

    /**
     * <code>string worker_id = 5;</code>
     * @return The workerId.
     */
    java.lang.String getWorkerId();
    /**
     * <code>string worker_id = 5;</code>
     * @return The bytes for workerId.
     */
    com.google.protobuf.ByteString
        getWorkerIdBytes();

    /**
     * <code>.conductor.proto.TaskResult.Status status = 6;</code>
     * @return The enum numeric value on the wire for status.
     */
    int getStatusValue();
    /**
     * <code>.conductor.proto.TaskResult.Status status = 6;</code>
     * @return The status.
     */
    com.netflix.conductor.proto.TaskResultPb.TaskResult.Status getStatus();

    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; output_data = 7;</code>
     */
    int getOutputDataCount();
    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; output_data = 7;</code>
     */
    boolean containsOutputData(
        java.lang.String key);
    /**
     * Use {@link #getOutputDataMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, com.google.protobuf.Value>
    getOutputData();
    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; output_data = 7;</code>
     */
    java.util.Map<java.lang.String, com.google.protobuf.Value>
    getOutputDataMap();
    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; output_data = 7;</code>
     */

    com.google.protobuf.Value getOutputDataOrDefault(
        java.lang.String key,
        com.google.protobuf.Value defaultValue);
    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; output_data = 7;</code>
     */

    com.google.protobuf.Value getOutputDataOrThrow(
        java.lang.String key);

    /**
     * <code>.google.protobuf.Any output_message = 8;</code>
     * @return Whether the outputMessage field is set.
     */
    boolean hasOutputMessage();
    /**
     * <code>.google.protobuf.Any output_message = 8;</code>
     * @return The outputMessage.
     */
    com.google.protobuf.Any getOutputMessage();
    /**
     * <code>.google.protobuf.Any output_message = 8;</code>
     */
    com.google.protobuf.AnyOrBuilder getOutputMessageOrBuilder();
  }
  /**
   * Protobuf type {@code conductor.proto.TaskResult}
   */
  public static final class TaskResult extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:conductor.proto.TaskResult)
      TaskResultOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TaskResult.newBuilder() to construct.
    private TaskResult(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TaskResult() {
      workflowInstanceId_ = "";
      taskId_ = "";
      reasonForIncompletion_ = "";
      workerId_ = "";
      status_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TaskResult();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TaskResult(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              workflowInstanceId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              taskId_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              reasonForIncompletion_ = s;
              break;
            }
            case 32: {

              callbackAfterSeconds_ = input.readInt64();
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              workerId_ = s;
              break;
            }
            case 48: {
              int rawValue = input.readEnum();

              status_ = rawValue;
              break;
            }
            case 58: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                outputData_ = com.google.protobuf.MapField.newMapField(
                    OutputDataDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<java.lang.String, com.google.protobuf.Value>
              outputData__ = input.readMessage(
                  OutputDataDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              outputData_.getMutableMap().put(
                  outputData__.getKey(), outputData__.getValue());
              break;
            }
            case 66: {
              com.google.protobuf.Any.Builder subBuilder = null;
              if (outputMessage_ != null) {
                subBuilder = outputMessage_.toBuilder();
              }
              outputMessage_ = input.readMessage(com.google.protobuf.Any.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(outputMessage_);
                outputMessage_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.netflix.conductor.proto.TaskResultPb.internal_static_conductor_proto_TaskResult_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 7:
          return internalGetOutputData();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.netflix.conductor.proto.TaskResultPb.internal_static_conductor_proto_TaskResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.netflix.conductor.proto.TaskResultPb.TaskResult.class, com.netflix.conductor.proto.TaskResultPb.TaskResult.Builder.class);
    }

    /**
     * Protobuf enum {@code conductor.proto.TaskResult.Status}
     */
    public enum Status
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>IN_PROGRESS = 0;</code>
       */
      IN_PROGRESS(0),
      /**
       * <code>FAILED = 1;</code>
       */
      FAILED(1),
      /**
       * <code>FAILED_WITH_TERMINAL_ERROR = 2;</code>
       */
      FAILED_WITH_TERMINAL_ERROR(2),
      /**
       * <code>COMPLETED = 3;</code>
       */
      COMPLETED(3),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>IN_PROGRESS = 0;</code>
       */
      public static final int IN_PROGRESS_VALUE = 0;
      /**
       * <code>FAILED = 1;</code>
       */
      public static final int FAILED_VALUE = 1;
      /**
       * <code>FAILED_WITH_TERMINAL_ERROR = 2;</code>
       */
      public static final int FAILED_WITH_TERMINAL_ERROR_VALUE = 2;
      /**
       * <code>COMPLETED = 3;</code>
       */
      public static final int COMPLETED_VALUE = 3;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Status valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static Status forNumber(int value) {
        switch (value) {
          case 0: return IN_PROGRESS;
          case 1: return FAILED;
          case 2: return FAILED_WITH_TERMINAL_ERROR;
          case 3: return COMPLETED;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Status>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Status> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Status>() {
              public Status findValueByNumber(int number) {
                return Status.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.netflix.conductor.proto.TaskResultPb.TaskResult.getDescriptor().getEnumTypes().get(0);
      }

      private static final Status[] VALUES = values();

      public static Status valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Status(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:conductor.proto.TaskResult.Status)
    }

    public static final int WORKFLOW_INSTANCE_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object workflowInstanceId_;
    /**
     * <code>string workflow_instance_id = 1;</code>
     * @return The workflowInstanceId.
     */
    @java.lang.Override
    public java.lang.String getWorkflowInstanceId() {
      java.lang.Object ref = workflowInstanceId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        workflowInstanceId_ = s;
        return s;
      }
    }
    /**
     * <code>string workflow_instance_id = 1;</code>
     * @return The bytes for workflowInstanceId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getWorkflowInstanceIdBytes() {
      java.lang.Object ref = workflowInstanceId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        workflowInstanceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TASK_ID_FIELD_NUMBER = 2;
    private volatile java.lang.Object taskId_;
    /**
     * <code>string task_id = 2;</code>
     * @return The taskId.
     */
    @java.lang.Override
    public java.lang.String getTaskId() {
      java.lang.Object ref = taskId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        taskId_ = s;
        return s;
      }
    }
    /**
     * <code>string task_id = 2;</code>
     * @return The bytes for taskId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTaskIdBytes() {
      java.lang.Object ref = taskId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        taskId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REASON_FOR_INCOMPLETION_FIELD_NUMBER = 3;
    private volatile java.lang.Object reasonForIncompletion_;
    /**
     * <code>string reason_for_incompletion = 3;</code>
     * @return The reasonForIncompletion.
     */
    @java.lang.Override
    public java.lang.String getReasonForIncompletion() {
      java.lang.Object ref = reasonForIncompletion_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        reasonForIncompletion_ = s;
        return s;
      }
    }
    /**
     * <code>string reason_for_incompletion = 3;</code>
     * @return The bytes for reasonForIncompletion.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getReasonForIncompletionBytes() {
      java.lang.Object ref = reasonForIncompletion_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        reasonForIncompletion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CALLBACK_AFTER_SECONDS_FIELD_NUMBER = 4;
    private long callbackAfterSeconds_;
    /**
     * <code>int64 callback_after_seconds = 4;</code>
     * @return The callbackAfterSeconds.
     */
    @java.lang.Override
    public long getCallbackAfterSeconds() {
      return callbackAfterSeconds_;
    }

    public static final int WORKER_ID_FIELD_NUMBER = 5;
    private volatile java.lang.Object workerId_;
    /**
     * <code>string worker_id = 5;</code>
     * @return The workerId.
     */
    @java.lang.Override
    public java.lang.String getWorkerId() {
      java.lang.Object ref = workerId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        workerId_ = s;
        return s;
      }
    }
    /**
     * <code>string worker_id = 5;</code>
     * @return The bytes for workerId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getWorkerIdBytes() {
      java.lang.Object ref = workerId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        workerId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATUS_FIELD_NUMBER = 6;
    private int status_;
    /**
     * <code>.conductor.proto.TaskResult.Status status = 6;</code>
     * @return The enum numeric value on the wire for status.
     */
    @java.lang.Override public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.conductor.proto.TaskResult.Status status = 6;</code>
     * @return The status.
     */
    @java.lang.Override public com.netflix.conductor.proto.TaskResultPb.TaskResult.Status getStatus() {
      @SuppressWarnings("deprecation")
      com.netflix.conductor.proto.TaskResultPb.TaskResult.Status result = com.netflix.conductor.proto.TaskResultPb.TaskResult.Status.valueOf(status_);
      return result == null ? com.netflix.conductor.proto.TaskResultPb.TaskResult.Status.UNRECOGNIZED : result;
    }

    public static final int OUTPUT_DATA_FIELD_NUMBER = 7;
    private static final class OutputDataDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, com.google.protobuf.Value> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, com.google.protobuf.Value>newDefaultInstance(
                  com.netflix.conductor.proto.TaskResultPb.internal_static_conductor_proto_TaskResult_OutputDataEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  com.google.protobuf.Value.getDefaultInstance());
    }
    private com.google.protobuf.MapField<
        java.lang.String, com.google.protobuf.Value> outputData_;
    private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.Value>
    internalGetOutputData() {
      if (outputData_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            OutputDataDefaultEntryHolder.defaultEntry);
      }
      return outputData_;
    }

    public int getOutputDataCount() {
      return internalGetOutputData().getMap().size();
    }
    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; output_data = 7;</code>
     */

    @java.lang.Override
    public boolean containsOutputData(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetOutputData().getMap().containsKey(key);
    }
    /**
     * Use {@link #getOutputDataMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.google.protobuf.Value> getOutputData() {
      return getOutputDataMap();
    }
    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; output_data = 7;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, com.google.protobuf.Value> getOutputDataMap() {
      return internalGetOutputData().getMap();
    }
    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; output_data = 7;</code>
     */
    @java.lang.Override

    public com.google.protobuf.Value getOutputDataOrDefault(
        java.lang.String key,
        com.google.protobuf.Value defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.google.protobuf.Value> map =
          internalGetOutputData().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .google.protobuf.Value&gt; output_data = 7;</code>
     */
    @java.lang.Override

    public com.google.protobuf.Value getOutputDataOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, com.google.protobuf.Value> map =
          internalGetOutputData().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public static final int OUTPUT_MESSAGE_FIELD_NUMBER = 8;
    private com.google.protobuf.Any outputMessage_;
    /**
     * <code>.google.protobuf.Any output_message = 8;</code>
     * @return Whether the outputMessage field is set.
     */
    @java.lang.Override
    public boolean hasOutputMessage() {
      return outputMessage_ != null;
    }
    /**
     * <code>.google.protobuf.Any output_message = 8;</code>
     * @return The outputMessage.
     */
    @java.lang.Override
    public com.google.protobuf.Any getOutputMessage() {
      return outputMessage_ == null ? com.google.protobuf.Any.getDefaultInstance() : outputMessage_;
    }
    /**
     * <code>.google.protobuf.Any output_message = 8;</code>
     */
    @java.lang.Override
    public com.google.protobuf.AnyOrBuilder getOutputMessageOrBuilder() {
      return getOutputMessage();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getWorkflowInstanceIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, workflowInstanceId_);
      }
      if (!getTaskIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, taskId_);
      }
      if (!getReasonForIncompletionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, reasonForIncompletion_);
      }
      if (callbackAfterSeconds_ != 0L) {
        output.writeInt64(4, callbackAfterSeconds_);
      }
      if (!getWorkerIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, workerId_);
      }
      if (status_ != com.netflix.conductor.proto.TaskResultPb.TaskResult.Status.IN_PROGRESS.getNumber()) {
        output.writeEnum(6, status_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetOutputData(),
          OutputDataDefaultEntryHolder.defaultEntry,
          7);
      if (outputMessage_ != null) {
        output.writeMessage(8, getOutputMessage());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getWorkflowInstanceIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, workflowInstanceId_);
      }
      if (!getTaskIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, taskId_);
      }
      if (!getReasonForIncompletionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, reasonForIncompletion_);
      }
      if (callbackAfterSeconds_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, callbackAfterSeconds_);
      }
      if (!getWorkerIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, workerId_);
      }
      if (status_ != com.netflix.conductor.proto.TaskResultPb.TaskResult.Status.IN_PROGRESS.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(6, status_);
      }
      for (java.util.Map.Entry<java.lang.String, com.google.protobuf.Value> entry
           : internalGetOutputData().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, com.google.protobuf.Value>
        outputData__ = OutputDataDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(7, outputData__);
      }
      if (outputMessage_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, getOutputMessage());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.netflix.conductor.proto.TaskResultPb.TaskResult)) {
        return super.equals(obj);
      }
      com.netflix.conductor.proto.TaskResultPb.TaskResult other = (com.netflix.conductor.proto.TaskResultPb.TaskResult) obj;

      if (!getWorkflowInstanceId()
          .equals(other.getWorkflowInstanceId())) return false;
      if (!getTaskId()
          .equals(other.getTaskId())) return false;
      if (!getReasonForIncompletion()
          .equals(other.getReasonForIncompletion())) return false;
      if (getCallbackAfterSeconds()
          != other.getCallbackAfterSeconds()) return false;
      if (!getWorkerId()
          .equals(other.getWorkerId())) return false;
      if (status_ != other.status_) return false;
      if (!internalGetOutputData().equals(
          other.internalGetOutputData())) return false;
      if (hasOutputMessage() != other.hasOutputMessage()) return false;
      if (hasOutputMessage()) {
        if (!getOutputMessage()
            .equals(other.getOutputMessage())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + WORKFLOW_INSTANCE_ID_FIELD_NUMBER;
      hash = (53 * hash) + getWorkflowInstanceId().hashCode();
      hash = (37 * hash) + TASK_ID_FIELD_NUMBER;
      hash = (53 * hash) + getTaskId().hashCode();
      hash = (37 * hash) + REASON_FOR_INCOMPLETION_FIELD_NUMBER;
      hash = (53 * hash) + getReasonForIncompletion().hashCode();
      hash = (37 * hash) + CALLBACK_AFTER_SECONDS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCallbackAfterSeconds());
      hash = (37 * hash) + WORKER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getWorkerId().hashCode();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + status_;
      if (!internalGetOutputData().getMap().isEmpty()) {
        hash = (37 * hash) + OUTPUT_DATA_FIELD_NUMBER;
        hash = (53 * hash) + internalGetOutputData().hashCode();
      }
      if (hasOutputMessage()) {
        hash = (37 * hash) + OUTPUT_MESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getOutputMessage().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.netflix.conductor.proto.TaskResultPb.TaskResult parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.netflix.conductor.proto.TaskResultPb.TaskResult parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.netflix.conductor.proto.TaskResultPb.TaskResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.netflix.conductor.proto.TaskResultPb.TaskResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.netflix.conductor.proto.TaskResultPb.TaskResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.netflix.conductor.proto.TaskResultPb.TaskResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.netflix.conductor.proto.TaskResultPb.TaskResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.netflix.conductor.proto.TaskResultPb.TaskResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.netflix.conductor.proto.TaskResultPb.TaskResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.netflix.conductor.proto.TaskResultPb.TaskResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.netflix.conductor.proto.TaskResultPb.TaskResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.netflix.conductor.proto.TaskResultPb.TaskResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.netflix.conductor.proto.TaskResultPb.TaskResult prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code conductor.proto.TaskResult}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:conductor.proto.TaskResult)
        com.netflix.conductor.proto.TaskResultPb.TaskResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.netflix.conductor.proto.TaskResultPb.internal_static_conductor_proto_TaskResult_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 7:
            return internalGetOutputData();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 7:
            return internalGetMutableOutputData();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.netflix.conductor.proto.TaskResultPb.internal_static_conductor_proto_TaskResult_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.netflix.conductor.proto.TaskResultPb.TaskResult.class, com.netflix.conductor.proto.TaskResultPb.TaskResult.Builder.class);
      }

      // Construct using com.netflix.conductor.proto.TaskResultPb.TaskResult.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        workflowInstanceId_ = "";

        taskId_ = "";

        reasonForIncompletion_ = "";

        callbackAfterSeconds_ = 0L;

        workerId_ = "";

        status_ = 0;

        internalGetMutableOutputData().clear();
        if (outputMessageBuilder_ == null) {
          outputMessage_ = null;
        } else {
          outputMessage_ = null;
          outputMessageBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.netflix.conductor.proto.TaskResultPb.internal_static_conductor_proto_TaskResult_descriptor;
      }

      @java.lang.Override
      public com.netflix.conductor.proto.TaskResultPb.TaskResult getDefaultInstanceForType() {
        return com.netflix.conductor.proto.TaskResultPb.TaskResult.getDefaultInstance();
      }

      @java.lang.Override
      public com.netflix.conductor.proto.TaskResultPb.TaskResult build() {
        com.netflix.conductor.proto.TaskResultPb.TaskResult result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.netflix.conductor.proto.TaskResultPb.TaskResult buildPartial() {
        com.netflix.conductor.proto.TaskResultPb.TaskResult result = new com.netflix.conductor.proto.TaskResultPb.TaskResult(this);
        int from_bitField0_ = bitField0_;
        result.workflowInstanceId_ = workflowInstanceId_;
        result.taskId_ = taskId_;
        result.reasonForIncompletion_ = reasonForIncompletion_;
        result.callbackAfterSeconds_ = callbackAfterSeconds_;
        result.workerId_ = workerId_;
        result.status_ = status_;
        result.outputData_ = internalGetOutputData();
        result.outputData_.makeImmutable();
        if (outputMessageBuilder_ == null) {
          result.outputMessage_ = outputMessage_;
        } else {
          result.outputMessage_ = outputMessageBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.netflix.conductor.proto.TaskResultPb.TaskResult) {
          return mergeFrom((com.netflix.conductor.proto.TaskResultPb.TaskResult)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.netflix.conductor.proto.TaskResultPb.TaskResult other) {
        if (other == com.netflix.conductor.proto.TaskResultPb.TaskResult.getDefaultInstance()) return this;
        if (!other.getWorkflowInstanceId().isEmpty()) {
          workflowInstanceId_ = other.workflowInstanceId_;
          onChanged();
        }
        if (!other.getTaskId().isEmpty()) {
          taskId_ = other.taskId_;
          onChanged();
        }
        if (!other.getReasonForIncompletion().isEmpty()) {
          reasonForIncompletion_ = other.reasonForIncompletion_;
          onChanged();
        }
        if (other.getCallbackAfterSeconds() != 0L) {
          setCallbackAfterSeconds(other.getCallbackAfterSeconds());
        }
        if (!other.getWorkerId().isEmpty()) {
          workerId_ = other.workerId_;
          onChanged();
        }
        if (other.status_ != 0) {
          setStatusValue(other.getStatusValue());
        }
        internalGetMutableOutputData().mergeFrom(
            other.internalGetOutputData());
        if (other.hasOutputMessage()) {
          mergeOutputMessage(other.getOutputMessage());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.netflix.conductor.proto.TaskResultPb.TaskResult parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.netflix.conductor.proto.TaskResultPb.TaskResult) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object workflowInstanceId_ = "";
      /**
       * <code>string workflow_instance_id = 1;</code>
       * @return The workflowInstanceId.
       */
      public java.lang.String getWorkflowInstanceId() {
        java.lang.Object ref = workflowInstanceId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          workflowInstanceId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string workflow_instance_id = 1;</code>
       * @return The bytes for workflowInstanceId.
       */
      public com.google.protobuf.ByteString
          getWorkflowInstanceIdBytes() {
        java.lang.Object ref = workflowInstanceId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          workflowInstanceId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string workflow_instance_id = 1;</code>
       * @param value The workflowInstanceId to set.
       * @return This builder for chaining.
       */
      public Builder setWorkflowInstanceId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        workflowInstanceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string workflow_instance_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearWorkflowInstanceId() {
        
        workflowInstanceId_ = getDefaultInstance().getWorkflowInstanceId();
        onChanged();
        return this;
      }
      /**
       * <code>string workflow_instance_id = 1;</code>
       * @param value The bytes for workflowInstanceId to set.
       * @return This builder for chaining.
       */
      public Builder setWorkflowInstanceIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        workflowInstanceId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object taskId_ = "";
      /**
       * <code>string task_id = 2;</code>
       * @return The taskId.
       */
      public java.lang.String getTaskId() {
        java.lang.Object ref = taskId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          taskId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string task_id = 2;</code>
       * @return The bytes for taskId.
       */
      public com.google.protobuf.ByteString
          getTaskIdBytes() {
        java.lang.Object ref = taskId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          taskId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string task_id = 2;</code>
       * @param value The taskId to set.
       * @return This builder for chaining.
       */
      public Builder setTaskId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        taskId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string task_id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTaskId() {
        
        taskId_ = getDefaultInstance().getTaskId();
        onChanged();
        return this;
      }
      /**
       * <code>string task_id = 2;</code>
       * @param value The bytes for taskId to set.
       * @return This builder for chaining.
       */
      public Builder setTaskIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        taskId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object reasonForIncompletion_ = "";
      /**
       * <code>string reason_for_incompletion = 3;</code>
       * @return The reasonForIncompletion.
       */
      public java.lang.String getReasonForIncompletion() {
        java.lang.Object ref = reasonForIncompletion_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          reasonForIncompletion_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string reason_for_incompletion = 3;</code>
       * @return The bytes for reasonForIncompletion.
       */
      public com.google.protobuf.ByteString
          getReasonForIncompletionBytes() {
        java.lang.Object ref = reasonForIncompletion_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          reasonForIncompletion_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string reason_for_incompletion = 3;</code>
       * @param value The reasonForIncompletion to set.
       * @return This builder for chaining.
       */
      public Builder setReasonForIncompletion(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        reasonForIncompletion_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string reason_for_incompletion = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearReasonForIncompletion() {
        
        reasonForIncompletion_ = getDefaultInstance().getReasonForIncompletion();
        onChanged();
        return this;
      }
      /**
       * <code>string reason_for_incompletion = 3;</code>
       * @param value The bytes for reasonForIncompletion to set.
       * @return This builder for chaining.
       */
      public Builder setReasonForIncompletionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        reasonForIncompletion_ = value;
        onChanged();
        return this;
      }

      private long callbackAfterSeconds_ ;
      /**
       * <code>int64 callback_after_seconds = 4;</code>
       * @return The callbackAfterSeconds.
       */
      @java.lang.Override
      public long getCallbackAfterSeconds() {
        return callbackAfterSeconds_;
      }
      /**
       * <code>int64 callback_after_seconds = 4;</code>
       * @param value The callbackAfterSeconds to set.
       * @return This builder for chaining.
       */
      public Builder setCallbackAfterSeconds(long value) {
        
        callbackAfterSeconds_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 callback_after_seconds = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearCallbackAfterSeconds() {
        
        callbackAfterSeconds_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object workerId_ = "";
      /**
       * <code>string worker_id = 5;</code>
       * @return The workerId.
       */
      public java.lang.String getWorkerId() {
        java.lang.Object ref = workerId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          workerId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string worker_id = 5;</code>
       * @return The bytes for workerId.
       */
      public com.google.protobuf.ByteString
          getWorkerIdBytes() {
        java.lang.Object ref = workerId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          workerId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string worker_id = 5;</code>
       * @param value The workerId to set.
       * @return This builder for chaining.
       */
      public Builder setWorkerId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        workerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string worker_id = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearWorkerId() {
        
        workerId_ = getDefaultInstance().getWorkerId();
        onChanged();
        return this;
      }
      /**
       * <code>string worker_id = 5;</code>
       * @param value The bytes for workerId to set.
       * @return This builder for chaining.
       */
      public Builder setWorkerIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        workerId_ = value;
        onChanged();
        return this;
      }

      private int status_ = 0;
      /**
       * <code>.conductor.proto.TaskResult.Status status = 6;</code>
       * @return The enum numeric value on the wire for status.
       */
      @java.lang.Override public int getStatusValue() {
        return status_;
      }
      /**
       * <code>.conductor.proto.TaskResult.Status status = 6;</code>
       * @param value The enum numeric value on the wire for status to set.
       * @return This builder for chaining.
       */
      public Builder setStatusValue(int value) {
        
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.conductor.proto.TaskResult.Status status = 6;</code>
       * @return The status.
       */
      @java.lang.Override
      public com.netflix.conductor.proto.TaskResultPb.TaskResult.Status getStatus() {
        @SuppressWarnings("deprecation")
        com.netflix.conductor.proto.TaskResultPb.TaskResult.Status result = com.netflix.conductor.proto.TaskResultPb.TaskResult.Status.valueOf(status_);
        return result == null ? com.netflix.conductor.proto.TaskResultPb.TaskResult.Status.UNRECOGNIZED : result;
      }
      /**
       * <code>.conductor.proto.TaskResult.Status status = 6;</code>
       * @param value The status to set.
       * @return This builder for chaining.
       */
      public Builder setStatus(com.netflix.conductor.proto.TaskResultPb.TaskResult.Status value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        status_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.conductor.proto.TaskResult.Status status = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatus() {
        
        status_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, com.google.protobuf.Value> outputData_;
      private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.Value>
      internalGetOutputData() {
        if (outputData_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              OutputDataDefaultEntryHolder.defaultEntry);
        }
        return outputData_;
      }
      private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.Value>
      internalGetMutableOutputData() {
        onChanged();;
        if (outputData_ == null) {
          outputData_ = com.google.protobuf.MapField.newMapField(
              OutputDataDefaultEntryHolder.defaultEntry);
        }
        if (!outputData_.isMutable()) {
          outputData_ = outputData_.copy();
        }
        return outputData_;
      }

      public int getOutputDataCount() {
        return internalGetOutputData().getMap().size();
      }
      /**
       * <code>map&lt;string, .google.protobuf.Value&gt; output_data = 7;</code>
       */

      @java.lang.Override
      public boolean containsOutputData(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetOutputData().getMap().containsKey(key);
      }
      /**
       * Use {@link #getOutputDataMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, com.google.protobuf.Value> getOutputData() {
        return getOutputDataMap();
      }
      /**
       * <code>map&lt;string, .google.protobuf.Value&gt; output_data = 7;</code>
       */
      @java.lang.Override

      public java.util.Map<java.lang.String, com.google.protobuf.Value> getOutputDataMap() {
        return internalGetOutputData().getMap();
      }
      /**
       * <code>map&lt;string, .google.protobuf.Value&gt; output_data = 7;</code>
       */
      @java.lang.Override

      public com.google.protobuf.Value getOutputDataOrDefault(
          java.lang.String key,
          com.google.protobuf.Value defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, com.google.protobuf.Value> map =
            internalGetOutputData().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, .google.protobuf.Value&gt; output_data = 7;</code>
       */
      @java.lang.Override

      public com.google.protobuf.Value getOutputDataOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, com.google.protobuf.Value> map =
            internalGetOutputData().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearOutputData() {
        internalGetMutableOutputData().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, .google.protobuf.Value&gt; output_data = 7;</code>
       */

      public Builder removeOutputData(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableOutputData().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, com.google.protobuf.Value>
      getMutableOutputData() {
        return internalGetMutableOutputData().getMutableMap();
      }
      /**
       * <code>map&lt;string, .google.protobuf.Value&gt; output_data = 7;</code>
       */
      public Builder putOutputData(
          java.lang.String key,
          com.google.protobuf.Value value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableOutputData().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, .google.protobuf.Value&gt; output_data = 7;</code>
       */

      public Builder putAllOutputData(
          java.util.Map<java.lang.String, com.google.protobuf.Value> values) {
        internalGetMutableOutputData().getMutableMap()
            .putAll(values);
        return this;
      }

      private com.google.protobuf.Any outputMessage_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> outputMessageBuilder_;
      /**
       * <code>.google.protobuf.Any output_message = 8;</code>
       * @return Whether the outputMessage field is set.
       */
      public boolean hasOutputMessage() {
        return outputMessageBuilder_ != null || outputMessage_ != null;
      }
      /**
       * <code>.google.protobuf.Any output_message = 8;</code>
       * @return The outputMessage.
       */
      public com.google.protobuf.Any getOutputMessage() {
        if (outputMessageBuilder_ == null) {
          return outputMessage_ == null ? com.google.protobuf.Any.getDefaultInstance() : outputMessage_;
        } else {
          return outputMessageBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Any output_message = 8;</code>
       */
      public Builder setOutputMessage(com.google.protobuf.Any value) {
        if (outputMessageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          outputMessage_ = value;
          onChanged();
        } else {
          outputMessageBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any output_message = 8;</code>
       */
      public Builder setOutputMessage(
          com.google.protobuf.Any.Builder builderForValue) {
        if (outputMessageBuilder_ == null) {
          outputMessage_ = builderForValue.build();
          onChanged();
        } else {
          outputMessageBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any output_message = 8;</code>
       */
      public Builder mergeOutputMessage(com.google.protobuf.Any value) {
        if (outputMessageBuilder_ == null) {
          if (outputMessage_ != null) {
            outputMessage_ =
              com.google.protobuf.Any.newBuilder(outputMessage_).mergeFrom(value).buildPartial();
          } else {
            outputMessage_ = value;
          }
          onChanged();
        } else {
          outputMessageBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any output_message = 8;</code>
       */
      public Builder clearOutputMessage() {
        if (outputMessageBuilder_ == null) {
          outputMessage_ = null;
          onChanged();
        } else {
          outputMessage_ = null;
          outputMessageBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any output_message = 8;</code>
       */
      public com.google.protobuf.Any.Builder getOutputMessageBuilder() {
        
        onChanged();
        return getOutputMessageFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Any output_message = 8;</code>
       */
      public com.google.protobuf.AnyOrBuilder getOutputMessageOrBuilder() {
        if (outputMessageBuilder_ != null) {
          return outputMessageBuilder_.getMessageOrBuilder();
        } else {
          return outputMessage_ == null ?
              com.google.protobuf.Any.getDefaultInstance() : outputMessage_;
        }
      }
      /**
       * <code>.google.protobuf.Any output_message = 8;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> 
          getOutputMessageFieldBuilder() {
        if (outputMessageBuilder_ == null) {
          outputMessageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                  getOutputMessage(),
                  getParentForChildren(),
                  isClean());
          outputMessage_ = null;
        }
        return outputMessageBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:conductor.proto.TaskResult)
    }

    // @@protoc_insertion_point(class_scope:conductor.proto.TaskResult)
    private static final com.netflix.conductor.proto.TaskResultPb.TaskResult DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.netflix.conductor.proto.TaskResultPb.TaskResult();
    }

    public static com.netflix.conductor.proto.TaskResultPb.TaskResult getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TaskResult>
        PARSER = new com.google.protobuf.AbstractParser<TaskResult>() {
      @java.lang.Override
      public TaskResult parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TaskResult(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TaskResult> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TaskResult> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.netflix.conductor.proto.TaskResultPb.TaskResult getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_conductor_proto_TaskResult_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_conductor_proto_TaskResult_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_conductor_proto_TaskResult_OutputDataEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_conductor_proto_TaskResult_OutputDataEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026model/taskresult.proto\022\017conductor.prot" +
      "o\032\034google/protobuf/struct.proto\032\031google/" +
      "protobuf/any.proto\"\324\003\n\nTaskResult\022\034\n\024wor" +
      "kflow_instance_id\030\001 \001(\t\022\017\n\007task_id\030\002 \001(\t" +
      "\022\037\n\027reason_for_incompletion\030\003 \001(\t\022\036\n\026cal" +
      "lback_after_seconds\030\004 \001(\003\022\021\n\tworker_id\030\005" +
      " \001(\t\0222\n\006status\030\006 \001(\0162\".conductor.proto.T" +
      "askResult.Status\022@\n\013output_data\030\007 \003(\0132+." +
      "conductor.proto.TaskResult.OutputDataEnt" +
      "ry\022,\n\016output_message\030\010 \001(\0132\024.google.prot" +
      "obuf.Any\032I\n\017OutputDataEntry\022\013\n\003key\030\001 \001(\t" +
      "\022%\n\005value\030\002 \001(\0132\026.google.protobuf.Value:" +
      "\0028\001\"T\n\006Status\022\017\n\013IN_PROGRESS\020\000\022\n\n\006FAILED" +
      "\020\001\022\036\n\032FAILED_WITH_TERMINAL_ERROR\020\002\022\r\n\tCO" +
      "MPLETED\020\003Bg\n\033com.netflix.conductor.proto" +
      "B\014TaskResultPbZ:github.com/netflix/condu" +
      "ctor/client/gogrpc/conductor/modelb\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.StructProto.getDescriptor(),
          com.google.protobuf.AnyProto.getDescriptor(),
        });
    internal_static_conductor_proto_TaskResult_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_conductor_proto_TaskResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_conductor_proto_TaskResult_descriptor,
        new java.lang.String[] { "WorkflowInstanceId", "TaskId", "ReasonForIncompletion", "CallbackAfterSeconds", "WorkerId", "Status", "OutputData", "OutputMessage", });
    internal_static_conductor_proto_TaskResult_OutputDataEntry_descriptor =
      internal_static_conductor_proto_TaskResult_descriptor.getNestedTypes().get(0);
    internal_static_conductor_proto_TaskResult_OutputDataEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_conductor_proto_TaskResult_OutputDataEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    com.google.protobuf.StructProto.getDescriptor();
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
