// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model/workflowsummary.proto

package com.netflix.conductor.proto;

public final class WorkflowSummaryPb {
  private WorkflowSummaryPb() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface WorkflowSummaryOrBuilder extends
      // @@protoc_insertion_point(interface_extends:conductor.proto.WorkflowSummary)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string workflow_type = 1;</code>
     * @return The workflowType.
     */
    java.lang.String getWorkflowType();
    /**
     * <code>string workflow_type = 1;</code>
     * @return The bytes for workflowType.
     */
    com.google.protobuf.ByteString
        getWorkflowTypeBytes();

    /**
     * <code>int32 version = 2;</code>
     * @return The version.
     */
    int getVersion();

    /**
     * <code>string workflow_id = 3;</code>
     * @return The workflowId.
     */
    java.lang.String getWorkflowId();
    /**
     * <code>string workflow_id = 3;</code>
     * @return The bytes for workflowId.
     */
    com.google.protobuf.ByteString
        getWorkflowIdBytes();

    /**
     * <code>string correlation_id = 4;</code>
     * @return The correlationId.
     */
    java.lang.String getCorrelationId();
    /**
     * <code>string correlation_id = 4;</code>
     * @return The bytes for correlationId.
     */
    com.google.protobuf.ByteString
        getCorrelationIdBytes();

    /**
     * <code>string start_time = 5;</code>
     * @return The startTime.
     */
    java.lang.String getStartTime();
    /**
     * <code>string start_time = 5;</code>
     * @return The bytes for startTime.
     */
    com.google.protobuf.ByteString
        getStartTimeBytes();

    /**
     * <code>string update_time = 6;</code>
     * @return The updateTime.
     */
    java.lang.String getUpdateTime();
    /**
     * <code>string update_time = 6;</code>
     * @return The bytes for updateTime.
     */
    com.google.protobuf.ByteString
        getUpdateTimeBytes();

    /**
     * <code>string end_time = 7;</code>
     * @return The endTime.
     */
    java.lang.String getEndTime();
    /**
     * <code>string end_time = 7;</code>
     * @return The bytes for endTime.
     */
    com.google.protobuf.ByteString
        getEndTimeBytes();

    /**
     * <code>.conductor.proto.Workflow.WorkflowStatus status = 8;</code>
     * @return The enum numeric value on the wire for status.
     */
    int getStatusValue();
    /**
     * <code>.conductor.proto.Workflow.WorkflowStatus status = 8;</code>
     * @return The status.
     */
    com.netflix.conductor.proto.WorkflowPb.Workflow.WorkflowStatus getStatus();

    /**
     * <code>string input = 9;</code>
     * @return The input.
     */
    java.lang.String getInput();
    /**
     * <code>string input = 9;</code>
     * @return The bytes for input.
     */
    com.google.protobuf.ByteString
        getInputBytes();

    /**
     * <code>string output = 10;</code>
     * @return The output.
     */
    java.lang.String getOutput();
    /**
     * <code>string output = 10;</code>
     * @return The bytes for output.
     */
    com.google.protobuf.ByteString
        getOutputBytes();

    /**
     * <code>string reason_for_incompletion = 11;</code>
     * @return The reasonForIncompletion.
     */
    java.lang.String getReasonForIncompletion();
    /**
     * <code>string reason_for_incompletion = 11;</code>
     * @return The bytes for reasonForIncompletion.
     */
    com.google.protobuf.ByteString
        getReasonForIncompletionBytes();

    /**
     * <code>int64 execution_time = 12;</code>
     * @return The executionTime.
     */
    long getExecutionTime();

    /**
     * <code>string event = 13;</code>
     * @return The event.
     */
    java.lang.String getEvent();
    /**
     * <code>string event = 13;</code>
     * @return The bytes for event.
     */
    com.google.protobuf.ByteString
        getEventBytes();

    /**
     * <code>string failed_reference_task_names = 14;</code>
     * @return The failedReferenceTaskNames.
     */
    java.lang.String getFailedReferenceTaskNames();
    /**
     * <code>string failed_reference_task_names = 14;</code>
     * @return The bytes for failedReferenceTaskNames.
     */
    com.google.protobuf.ByteString
        getFailedReferenceTaskNamesBytes();

    /**
     * <code>string external_input_payload_storage_path = 15;</code>
     * @return The externalInputPayloadStoragePath.
     */
    java.lang.String getExternalInputPayloadStoragePath();
    /**
     * <code>string external_input_payload_storage_path = 15;</code>
     * @return The bytes for externalInputPayloadStoragePath.
     */
    com.google.protobuf.ByteString
        getExternalInputPayloadStoragePathBytes();

    /**
     * <code>string external_output_payload_storage_path = 16;</code>
     * @return The externalOutputPayloadStoragePath.
     */
    java.lang.String getExternalOutputPayloadStoragePath();
    /**
     * <code>string external_output_payload_storage_path = 16;</code>
     * @return The bytes for externalOutputPayloadStoragePath.
     */
    com.google.protobuf.ByteString
        getExternalOutputPayloadStoragePathBytes();

    /**
     * <code>int32 priority = 17;</code>
     * @return The priority.
     */
    int getPriority();
  }
  /**
   * Protobuf type {@code conductor.proto.WorkflowSummary}
   */
  public static final class WorkflowSummary extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:conductor.proto.WorkflowSummary)
      WorkflowSummaryOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use WorkflowSummary.newBuilder() to construct.
    private WorkflowSummary(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private WorkflowSummary() {
      workflowType_ = "";
      workflowId_ = "";
      correlationId_ = "";
      startTime_ = "";
      updateTime_ = "";
      endTime_ = "";
      status_ = 0;
      input_ = "";
      output_ = "";
      reasonForIncompletion_ = "";
      event_ = "";
      failedReferenceTaskNames_ = "";
      externalInputPayloadStoragePath_ = "";
      externalOutputPayloadStoragePath_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new WorkflowSummary();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private WorkflowSummary(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              workflowType_ = s;
              break;
            }
            case 16: {

              version_ = input.readInt32();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              workflowId_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              correlationId_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              startTime_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              updateTime_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              endTime_ = s;
              break;
            }
            case 64: {
              int rawValue = input.readEnum();

              status_ = rawValue;
              break;
            }
            case 74: {
              java.lang.String s = input.readStringRequireUtf8();

              input_ = s;
              break;
            }
            case 82: {
              java.lang.String s = input.readStringRequireUtf8();

              output_ = s;
              break;
            }
            case 90: {
              java.lang.String s = input.readStringRequireUtf8();

              reasonForIncompletion_ = s;
              break;
            }
            case 96: {

              executionTime_ = input.readInt64();
              break;
            }
            case 106: {
              java.lang.String s = input.readStringRequireUtf8();

              event_ = s;
              break;
            }
            case 114: {
              java.lang.String s = input.readStringRequireUtf8();

              failedReferenceTaskNames_ = s;
              break;
            }
            case 122: {
              java.lang.String s = input.readStringRequireUtf8();

              externalInputPayloadStoragePath_ = s;
              break;
            }
            case 130: {
              java.lang.String s = input.readStringRequireUtf8();

              externalOutputPayloadStoragePath_ = s;
              break;
            }
            case 136: {

              priority_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.netflix.conductor.proto.WorkflowSummaryPb.internal_static_conductor_proto_WorkflowSummary_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.netflix.conductor.proto.WorkflowSummaryPb.internal_static_conductor_proto_WorkflowSummary_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.netflix.conductor.proto.WorkflowSummaryPb.WorkflowSummary.class, com.netflix.conductor.proto.WorkflowSummaryPb.WorkflowSummary.Builder.class);
    }

    public static final int WORKFLOW_TYPE_FIELD_NUMBER = 1;
    private volatile java.lang.Object workflowType_;
    /**
     * <code>string workflow_type = 1;</code>
     * @return The workflowType.
     */
    @java.lang.Override
    public java.lang.String getWorkflowType() {
      java.lang.Object ref = workflowType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        workflowType_ = s;
        return s;
      }
    }
    /**
     * <code>string workflow_type = 1;</code>
     * @return The bytes for workflowType.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getWorkflowTypeBytes() {
      java.lang.Object ref = workflowType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        workflowType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VERSION_FIELD_NUMBER = 2;
    private int version_;
    /**
     * <code>int32 version = 2;</code>
     * @return The version.
     */
    @java.lang.Override
    public int getVersion() {
      return version_;
    }

    public static final int WORKFLOW_ID_FIELD_NUMBER = 3;
    private volatile java.lang.Object workflowId_;
    /**
     * <code>string workflow_id = 3;</code>
     * @return The workflowId.
     */
    @java.lang.Override
    public java.lang.String getWorkflowId() {
      java.lang.Object ref = workflowId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        workflowId_ = s;
        return s;
      }
    }
    /**
     * <code>string workflow_id = 3;</code>
     * @return The bytes for workflowId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getWorkflowIdBytes() {
      java.lang.Object ref = workflowId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        workflowId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CORRELATION_ID_FIELD_NUMBER = 4;
    private volatile java.lang.Object correlationId_;
    /**
     * <code>string correlation_id = 4;</code>
     * @return The correlationId.
     */
    @java.lang.Override
    public java.lang.String getCorrelationId() {
      java.lang.Object ref = correlationId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        correlationId_ = s;
        return s;
      }
    }
    /**
     * <code>string correlation_id = 4;</code>
     * @return The bytes for correlationId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCorrelationIdBytes() {
      java.lang.Object ref = correlationId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        correlationId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int START_TIME_FIELD_NUMBER = 5;
    private volatile java.lang.Object startTime_;
    /**
     * <code>string start_time = 5;</code>
     * @return The startTime.
     */
    @java.lang.Override
    public java.lang.String getStartTime() {
      java.lang.Object ref = startTime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        startTime_ = s;
        return s;
      }
    }
    /**
     * <code>string start_time = 5;</code>
     * @return The bytes for startTime.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getStartTimeBytes() {
      java.lang.Object ref = startTime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        startTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int UPDATE_TIME_FIELD_NUMBER = 6;
    private volatile java.lang.Object updateTime_;
    /**
     * <code>string update_time = 6;</code>
     * @return The updateTime.
     */
    @java.lang.Override
    public java.lang.String getUpdateTime() {
      java.lang.Object ref = updateTime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        updateTime_ = s;
        return s;
      }
    }
    /**
     * <code>string update_time = 6;</code>
     * @return The bytes for updateTime.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUpdateTimeBytes() {
      java.lang.Object ref = updateTime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        updateTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int END_TIME_FIELD_NUMBER = 7;
    private volatile java.lang.Object endTime_;
    /**
     * <code>string end_time = 7;</code>
     * @return The endTime.
     */
    @java.lang.Override
    public java.lang.String getEndTime() {
      java.lang.Object ref = endTime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        endTime_ = s;
        return s;
      }
    }
    /**
     * <code>string end_time = 7;</code>
     * @return The bytes for endTime.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEndTimeBytes() {
      java.lang.Object ref = endTime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        endTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATUS_FIELD_NUMBER = 8;
    private int status_;
    /**
     * <code>.conductor.proto.Workflow.WorkflowStatus status = 8;</code>
     * @return The enum numeric value on the wire for status.
     */
    @java.lang.Override public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.conductor.proto.Workflow.WorkflowStatus status = 8;</code>
     * @return The status.
     */
    @java.lang.Override public com.netflix.conductor.proto.WorkflowPb.Workflow.WorkflowStatus getStatus() {
      @SuppressWarnings("deprecation")
      com.netflix.conductor.proto.WorkflowPb.Workflow.WorkflowStatus result = com.netflix.conductor.proto.WorkflowPb.Workflow.WorkflowStatus.valueOf(status_);
      return result == null ? com.netflix.conductor.proto.WorkflowPb.Workflow.WorkflowStatus.UNRECOGNIZED : result;
    }

    public static final int INPUT_FIELD_NUMBER = 9;
    private volatile java.lang.Object input_;
    /**
     * <code>string input = 9;</code>
     * @return The input.
     */
    @java.lang.Override
    public java.lang.String getInput() {
      java.lang.Object ref = input_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        input_ = s;
        return s;
      }
    }
    /**
     * <code>string input = 9;</code>
     * @return The bytes for input.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getInputBytes() {
      java.lang.Object ref = input_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        input_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OUTPUT_FIELD_NUMBER = 10;
    private volatile java.lang.Object output_;
    /**
     * <code>string output = 10;</code>
     * @return The output.
     */
    @java.lang.Override
    public java.lang.String getOutput() {
      java.lang.Object ref = output_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        output_ = s;
        return s;
      }
    }
    /**
     * <code>string output = 10;</code>
     * @return The bytes for output.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getOutputBytes() {
      java.lang.Object ref = output_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        output_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REASON_FOR_INCOMPLETION_FIELD_NUMBER = 11;
    private volatile java.lang.Object reasonForIncompletion_;
    /**
     * <code>string reason_for_incompletion = 11;</code>
     * @return The reasonForIncompletion.
     */
    @java.lang.Override
    public java.lang.String getReasonForIncompletion() {
      java.lang.Object ref = reasonForIncompletion_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        reasonForIncompletion_ = s;
        return s;
      }
    }
    /**
     * <code>string reason_for_incompletion = 11;</code>
     * @return The bytes for reasonForIncompletion.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getReasonForIncompletionBytes() {
      java.lang.Object ref = reasonForIncompletion_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        reasonForIncompletion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EXECUTION_TIME_FIELD_NUMBER = 12;
    private long executionTime_;
    /**
     * <code>int64 execution_time = 12;</code>
     * @return The executionTime.
     */
    @java.lang.Override
    public long getExecutionTime() {
      return executionTime_;
    }

    public static final int EVENT_FIELD_NUMBER = 13;
    private volatile java.lang.Object event_;
    /**
     * <code>string event = 13;</code>
     * @return The event.
     */
    @java.lang.Override
    public java.lang.String getEvent() {
      java.lang.Object ref = event_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        event_ = s;
        return s;
      }
    }
    /**
     * <code>string event = 13;</code>
     * @return The bytes for event.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEventBytes() {
      java.lang.Object ref = event_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        event_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FAILED_REFERENCE_TASK_NAMES_FIELD_NUMBER = 14;
    private volatile java.lang.Object failedReferenceTaskNames_;
    /**
     * <code>string failed_reference_task_names = 14;</code>
     * @return The failedReferenceTaskNames.
     */
    @java.lang.Override
    public java.lang.String getFailedReferenceTaskNames() {
      java.lang.Object ref = failedReferenceTaskNames_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        failedReferenceTaskNames_ = s;
        return s;
      }
    }
    /**
     * <code>string failed_reference_task_names = 14;</code>
     * @return The bytes for failedReferenceTaskNames.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFailedReferenceTaskNamesBytes() {
      java.lang.Object ref = failedReferenceTaskNames_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        failedReferenceTaskNames_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EXTERNAL_INPUT_PAYLOAD_STORAGE_PATH_FIELD_NUMBER = 15;
    private volatile java.lang.Object externalInputPayloadStoragePath_;
    /**
     * <code>string external_input_payload_storage_path = 15;</code>
     * @return The externalInputPayloadStoragePath.
     */
    @java.lang.Override
    public java.lang.String getExternalInputPayloadStoragePath() {
      java.lang.Object ref = externalInputPayloadStoragePath_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        externalInputPayloadStoragePath_ = s;
        return s;
      }
    }
    /**
     * <code>string external_input_payload_storage_path = 15;</code>
     * @return The bytes for externalInputPayloadStoragePath.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getExternalInputPayloadStoragePathBytes() {
      java.lang.Object ref = externalInputPayloadStoragePath_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        externalInputPayloadStoragePath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EXTERNAL_OUTPUT_PAYLOAD_STORAGE_PATH_FIELD_NUMBER = 16;
    private volatile java.lang.Object externalOutputPayloadStoragePath_;
    /**
     * <code>string external_output_payload_storage_path = 16;</code>
     * @return The externalOutputPayloadStoragePath.
     */
    @java.lang.Override
    public java.lang.String getExternalOutputPayloadStoragePath() {
      java.lang.Object ref = externalOutputPayloadStoragePath_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        externalOutputPayloadStoragePath_ = s;
        return s;
      }
    }
    /**
     * <code>string external_output_payload_storage_path = 16;</code>
     * @return The bytes for externalOutputPayloadStoragePath.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getExternalOutputPayloadStoragePathBytes() {
      java.lang.Object ref = externalOutputPayloadStoragePath_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        externalOutputPayloadStoragePath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PRIORITY_FIELD_NUMBER = 17;
    private int priority_;
    /**
     * <code>int32 priority = 17;</code>
     * @return The priority.
     */
    @java.lang.Override
    public int getPriority() {
      return priority_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getWorkflowTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, workflowType_);
      }
      if (version_ != 0) {
        output.writeInt32(2, version_);
      }
      if (!getWorkflowIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, workflowId_);
      }
      if (!getCorrelationIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, correlationId_);
      }
      if (!getStartTimeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, startTime_);
      }
      if (!getUpdateTimeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, updateTime_);
      }
      if (!getEndTimeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, endTime_);
      }
      if (status_ != com.netflix.conductor.proto.WorkflowPb.Workflow.WorkflowStatus.RUNNING.getNumber()) {
        output.writeEnum(8, status_);
      }
      if (!getInputBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, input_);
      }
      if (!getOutputBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, output_);
      }
      if (!getReasonForIncompletionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 11, reasonForIncompletion_);
      }
      if (executionTime_ != 0L) {
        output.writeInt64(12, executionTime_);
      }
      if (!getEventBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 13, event_);
      }
      if (!getFailedReferenceTaskNamesBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 14, failedReferenceTaskNames_);
      }
      if (!getExternalInputPayloadStoragePathBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 15, externalInputPayloadStoragePath_);
      }
      if (!getExternalOutputPayloadStoragePathBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 16, externalOutputPayloadStoragePath_);
      }
      if (priority_ != 0) {
        output.writeInt32(17, priority_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getWorkflowTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, workflowType_);
      }
      if (version_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, version_);
      }
      if (!getWorkflowIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, workflowId_);
      }
      if (!getCorrelationIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, correlationId_);
      }
      if (!getStartTimeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, startTime_);
      }
      if (!getUpdateTimeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, updateTime_);
      }
      if (!getEndTimeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, endTime_);
      }
      if (status_ != com.netflix.conductor.proto.WorkflowPb.Workflow.WorkflowStatus.RUNNING.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(8, status_);
      }
      if (!getInputBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, input_);
      }
      if (!getOutputBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, output_);
      }
      if (!getReasonForIncompletionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, reasonForIncompletion_);
      }
      if (executionTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(12, executionTime_);
      }
      if (!getEventBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, event_);
      }
      if (!getFailedReferenceTaskNamesBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(14, failedReferenceTaskNames_);
      }
      if (!getExternalInputPayloadStoragePathBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(15, externalInputPayloadStoragePath_);
      }
      if (!getExternalOutputPayloadStoragePathBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(16, externalOutputPayloadStoragePath_);
      }
      if (priority_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(17, priority_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.netflix.conductor.proto.WorkflowSummaryPb.WorkflowSummary)) {
        return super.equals(obj);
      }
      com.netflix.conductor.proto.WorkflowSummaryPb.WorkflowSummary other = (com.netflix.conductor.proto.WorkflowSummaryPb.WorkflowSummary) obj;

      if (!getWorkflowType()
          .equals(other.getWorkflowType())) return false;
      if (getVersion()
          != other.getVersion()) return false;
      if (!getWorkflowId()
          .equals(other.getWorkflowId())) return false;
      if (!getCorrelationId()
          .equals(other.getCorrelationId())) return false;
      if (!getStartTime()
          .equals(other.getStartTime())) return false;
      if (!getUpdateTime()
          .equals(other.getUpdateTime())) return false;
      if (!getEndTime()
          .equals(other.getEndTime())) return false;
      if (status_ != other.status_) return false;
      if (!getInput()
          .equals(other.getInput())) return false;
      if (!getOutput()
          .equals(other.getOutput())) return false;
      if (!getReasonForIncompletion()
          .equals(other.getReasonForIncompletion())) return false;
      if (getExecutionTime()
          != other.getExecutionTime()) return false;
      if (!getEvent()
          .equals(other.getEvent())) return false;
      if (!getFailedReferenceTaskNames()
          .equals(other.getFailedReferenceTaskNames())) return false;
      if (!getExternalInputPayloadStoragePath()
          .equals(other.getExternalInputPayloadStoragePath())) return false;
      if (!getExternalOutputPayloadStoragePath()
          .equals(other.getExternalOutputPayloadStoragePath())) return false;
      if (getPriority()
          != other.getPriority()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + WORKFLOW_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getWorkflowType().hashCode();
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion();
      hash = (37 * hash) + WORKFLOW_ID_FIELD_NUMBER;
      hash = (53 * hash) + getWorkflowId().hashCode();
      hash = (37 * hash) + CORRELATION_ID_FIELD_NUMBER;
      hash = (53 * hash) + getCorrelationId().hashCode();
      hash = (37 * hash) + START_TIME_FIELD_NUMBER;
      hash = (53 * hash) + getStartTime().hashCode();
      hash = (37 * hash) + UPDATE_TIME_FIELD_NUMBER;
      hash = (53 * hash) + getUpdateTime().hashCode();
      hash = (37 * hash) + END_TIME_FIELD_NUMBER;
      hash = (53 * hash) + getEndTime().hashCode();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + status_;
      hash = (37 * hash) + INPUT_FIELD_NUMBER;
      hash = (53 * hash) + getInput().hashCode();
      hash = (37 * hash) + OUTPUT_FIELD_NUMBER;
      hash = (53 * hash) + getOutput().hashCode();
      hash = (37 * hash) + REASON_FOR_INCOMPLETION_FIELD_NUMBER;
      hash = (53 * hash) + getReasonForIncompletion().hashCode();
      hash = (37 * hash) + EXECUTION_TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getExecutionTime());
      hash = (37 * hash) + EVENT_FIELD_NUMBER;
      hash = (53 * hash) + getEvent().hashCode();
      hash = (37 * hash) + FAILED_REFERENCE_TASK_NAMES_FIELD_NUMBER;
      hash = (53 * hash) + getFailedReferenceTaskNames().hashCode();
      hash = (37 * hash) + EXTERNAL_INPUT_PAYLOAD_STORAGE_PATH_FIELD_NUMBER;
      hash = (53 * hash) + getExternalInputPayloadStoragePath().hashCode();
      hash = (37 * hash) + EXTERNAL_OUTPUT_PAYLOAD_STORAGE_PATH_FIELD_NUMBER;
      hash = (53 * hash) + getExternalOutputPayloadStoragePath().hashCode();
      hash = (37 * hash) + PRIORITY_FIELD_NUMBER;
      hash = (53 * hash) + getPriority();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.netflix.conductor.proto.WorkflowSummaryPb.WorkflowSummary parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.netflix.conductor.proto.WorkflowSummaryPb.WorkflowSummary parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.netflix.conductor.proto.WorkflowSummaryPb.WorkflowSummary parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.netflix.conductor.proto.WorkflowSummaryPb.WorkflowSummary parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.netflix.conductor.proto.WorkflowSummaryPb.WorkflowSummary parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.netflix.conductor.proto.WorkflowSummaryPb.WorkflowSummary parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.netflix.conductor.proto.WorkflowSummaryPb.WorkflowSummary parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.netflix.conductor.proto.WorkflowSummaryPb.WorkflowSummary parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.netflix.conductor.proto.WorkflowSummaryPb.WorkflowSummary parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.netflix.conductor.proto.WorkflowSummaryPb.WorkflowSummary parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.netflix.conductor.proto.WorkflowSummaryPb.WorkflowSummary parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.netflix.conductor.proto.WorkflowSummaryPb.WorkflowSummary parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.netflix.conductor.proto.WorkflowSummaryPb.WorkflowSummary prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code conductor.proto.WorkflowSummary}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:conductor.proto.WorkflowSummary)
        com.netflix.conductor.proto.WorkflowSummaryPb.WorkflowSummaryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.netflix.conductor.proto.WorkflowSummaryPb.internal_static_conductor_proto_WorkflowSummary_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.netflix.conductor.proto.WorkflowSummaryPb.internal_static_conductor_proto_WorkflowSummary_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.netflix.conductor.proto.WorkflowSummaryPb.WorkflowSummary.class, com.netflix.conductor.proto.WorkflowSummaryPb.WorkflowSummary.Builder.class);
      }

      // Construct using com.netflix.conductor.proto.WorkflowSummaryPb.WorkflowSummary.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        workflowType_ = "";

        version_ = 0;

        workflowId_ = "";

        correlationId_ = "";

        startTime_ = "";

        updateTime_ = "";

        endTime_ = "";

        status_ = 0;

        input_ = "";

        output_ = "";

        reasonForIncompletion_ = "";

        executionTime_ = 0L;

        event_ = "";

        failedReferenceTaskNames_ = "";

        externalInputPayloadStoragePath_ = "";

        externalOutputPayloadStoragePath_ = "";

        priority_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.netflix.conductor.proto.WorkflowSummaryPb.internal_static_conductor_proto_WorkflowSummary_descriptor;
      }

      @java.lang.Override
      public com.netflix.conductor.proto.WorkflowSummaryPb.WorkflowSummary getDefaultInstanceForType() {
        return com.netflix.conductor.proto.WorkflowSummaryPb.WorkflowSummary.getDefaultInstance();
      }

      @java.lang.Override
      public com.netflix.conductor.proto.WorkflowSummaryPb.WorkflowSummary build() {
        com.netflix.conductor.proto.WorkflowSummaryPb.WorkflowSummary result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.netflix.conductor.proto.WorkflowSummaryPb.WorkflowSummary buildPartial() {
        com.netflix.conductor.proto.WorkflowSummaryPb.WorkflowSummary result = new com.netflix.conductor.proto.WorkflowSummaryPb.WorkflowSummary(this);
        result.workflowType_ = workflowType_;
        result.version_ = version_;
        result.workflowId_ = workflowId_;
        result.correlationId_ = correlationId_;
        result.startTime_ = startTime_;
        result.updateTime_ = updateTime_;
        result.endTime_ = endTime_;
        result.status_ = status_;
        result.input_ = input_;
        result.output_ = output_;
        result.reasonForIncompletion_ = reasonForIncompletion_;
        result.executionTime_ = executionTime_;
        result.event_ = event_;
        result.failedReferenceTaskNames_ = failedReferenceTaskNames_;
        result.externalInputPayloadStoragePath_ = externalInputPayloadStoragePath_;
        result.externalOutputPayloadStoragePath_ = externalOutputPayloadStoragePath_;
        result.priority_ = priority_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.netflix.conductor.proto.WorkflowSummaryPb.WorkflowSummary) {
          return mergeFrom((com.netflix.conductor.proto.WorkflowSummaryPb.WorkflowSummary)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.netflix.conductor.proto.WorkflowSummaryPb.WorkflowSummary other) {
        if (other == com.netflix.conductor.proto.WorkflowSummaryPb.WorkflowSummary.getDefaultInstance()) return this;
        if (!other.getWorkflowType().isEmpty()) {
          workflowType_ = other.workflowType_;
          onChanged();
        }
        if (other.getVersion() != 0) {
          setVersion(other.getVersion());
        }
        if (!other.getWorkflowId().isEmpty()) {
          workflowId_ = other.workflowId_;
          onChanged();
        }
        if (!other.getCorrelationId().isEmpty()) {
          correlationId_ = other.correlationId_;
          onChanged();
        }
        if (!other.getStartTime().isEmpty()) {
          startTime_ = other.startTime_;
          onChanged();
        }
        if (!other.getUpdateTime().isEmpty()) {
          updateTime_ = other.updateTime_;
          onChanged();
        }
        if (!other.getEndTime().isEmpty()) {
          endTime_ = other.endTime_;
          onChanged();
        }
        if (other.status_ != 0) {
          setStatusValue(other.getStatusValue());
        }
        if (!other.getInput().isEmpty()) {
          input_ = other.input_;
          onChanged();
        }
        if (!other.getOutput().isEmpty()) {
          output_ = other.output_;
          onChanged();
        }
        if (!other.getReasonForIncompletion().isEmpty()) {
          reasonForIncompletion_ = other.reasonForIncompletion_;
          onChanged();
        }
        if (other.getExecutionTime() != 0L) {
          setExecutionTime(other.getExecutionTime());
        }
        if (!other.getEvent().isEmpty()) {
          event_ = other.event_;
          onChanged();
        }
        if (!other.getFailedReferenceTaskNames().isEmpty()) {
          failedReferenceTaskNames_ = other.failedReferenceTaskNames_;
          onChanged();
        }
        if (!other.getExternalInputPayloadStoragePath().isEmpty()) {
          externalInputPayloadStoragePath_ = other.externalInputPayloadStoragePath_;
          onChanged();
        }
        if (!other.getExternalOutputPayloadStoragePath().isEmpty()) {
          externalOutputPayloadStoragePath_ = other.externalOutputPayloadStoragePath_;
          onChanged();
        }
        if (other.getPriority() != 0) {
          setPriority(other.getPriority());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.netflix.conductor.proto.WorkflowSummaryPb.WorkflowSummary parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.netflix.conductor.proto.WorkflowSummaryPb.WorkflowSummary) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object workflowType_ = "";
      /**
       * <code>string workflow_type = 1;</code>
       * @return The workflowType.
       */
      public java.lang.String getWorkflowType() {
        java.lang.Object ref = workflowType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          workflowType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string workflow_type = 1;</code>
       * @return The bytes for workflowType.
       */
      public com.google.protobuf.ByteString
          getWorkflowTypeBytes() {
        java.lang.Object ref = workflowType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          workflowType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string workflow_type = 1;</code>
       * @param value The workflowType to set.
       * @return This builder for chaining.
       */
      public Builder setWorkflowType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        workflowType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string workflow_type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearWorkflowType() {
        
        workflowType_ = getDefaultInstance().getWorkflowType();
        onChanged();
        return this;
      }
      /**
       * <code>string workflow_type = 1;</code>
       * @param value The bytes for workflowType to set.
       * @return This builder for chaining.
       */
      public Builder setWorkflowTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        workflowType_ = value;
        onChanged();
        return this;
      }

      private int version_ ;
      /**
       * <code>int32 version = 2;</code>
       * @return The version.
       */
      @java.lang.Override
      public int getVersion() {
        return version_;
      }
      /**
       * <code>int32 version = 2;</code>
       * @param value The version to set.
       * @return This builder for chaining.
       */
      public Builder setVersion(int value) {
        
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 version = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearVersion() {
        
        version_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object workflowId_ = "";
      /**
       * <code>string workflow_id = 3;</code>
       * @return The workflowId.
       */
      public java.lang.String getWorkflowId() {
        java.lang.Object ref = workflowId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          workflowId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string workflow_id = 3;</code>
       * @return The bytes for workflowId.
       */
      public com.google.protobuf.ByteString
          getWorkflowIdBytes() {
        java.lang.Object ref = workflowId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          workflowId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string workflow_id = 3;</code>
       * @param value The workflowId to set.
       * @return This builder for chaining.
       */
      public Builder setWorkflowId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        workflowId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string workflow_id = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearWorkflowId() {
        
        workflowId_ = getDefaultInstance().getWorkflowId();
        onChanged();
        return this;
      }
      /**
       * <code>string workflow_id = 3;</code>
       * @param value The bytes for workflowId to set.
       * @return This builder for chaining.
       */
      public Builder setWorkflowIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        workflowId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object correlationId_ = "";
      /**
       * <code>string correlation_id = 4;</code>
       * @return The correlationId.
       */
      public java.lang.String getCorrelationId() {
        java.lang.Object ref = correlationId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          correlationId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string correlation_id = 4;</code>
       * @return The bytes for correlationId.
       */
      public com.google.protobuf.ByteString
          getCorrelationIdBytes() {
        java.lang.Object ref = correlationId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          correlationId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string correlation_id = 4;</code>
       * @param value The correlationId to set.
       * @return This builder for chaining.
       */
      public Builder setCorrelationId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        correlationId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string correlation_id = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearCorrelationId() {
        
        correlationId_ = getDefaultInstance().getCorrelationId();
        onChanged();
        return this;
      }
      /**
       * <code>string correlation_id = 4;</code>
       * @param value The bytes for correlationId to set.
       * @return This builder for chaining.
       */
      public Builder setCorrelationIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        correlationId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object startTime_ = "";
      /**
       * <code>string start_time = 5;</code>
       * @return The startTime.
       */
      public java.lang.String getStartTime() {
        java.lang.Object ref = startTime_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          startTime_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string start_time = 5;</code>
       * @return The bytes for startTime.
       */
      public com.google.protobuf.ByteString
          getStartTimeBytes() {
        java.lang.Object ref = startTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          startTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string start_time = 5;</code>
       * @param value The startTime to set.
       * @return This builder for chaining.
       */
      public Builder setStartTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        startTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string start_time = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearStartTime() {
        
        startTime_ = getDefaultInstance().getStartTime();
        onChanged();
        return this;
      }
      /**
       * <code>string start_time = 5;</code>
       * @param value The bytes for startTime to set.
       * @return This builder for chaining.
       */
      public Builder setStartTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        startTime_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object updateTime_ = "";
      /**
       * <code>string update_time = 6;</code>
       * @return The updateTime.
       */
      public java.lang.String getUpdateTime() {
        java.lang.Object ref = updateTime_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          updateTime_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string update_time = 6;</code>
       * @return The bytes for updateTime.
       */
      public com.google.protobuf.ByteString
          getUpdateTimeBytes() {
        java.lang.Object ref = updateTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          updateTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string update_time = 6;</code>
       * @param value The updateTime to set.
       * @return This builder for chaining.
       */
      public Builder setUpdateTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        updateTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string update_time = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearUpdateTime() {
        
        updateTime_ = getDefaultInstance().getUpdateTime();
        onChanged();
        return this;
      }
      /**
       * <code>string update_time = 6;</code>
       * @param value The bytes for updateTime to set.
       * @return This builder for chaining.
       */
      public Builder setUpdateTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        updateTime_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object endTime_ = "";
      /**
       * <code>string end_time = 7;</code>
       * @return The endTime.
       */
      public java.lang.String getEndTime() {
        java.lang.Object ref = endTime_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          endTime_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string end_time = 7;</code>
       * @return The bytes for endTime.
       */
      public com.google.protobuf.ByteString
          getEndTimeBytes() {
        java.lang.Object ref = endTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          endTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string end_time = 7;</code>
       * @param value The endTime to set.
       * @return This builder for chaining.
       */
      public Builder setEndTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        endTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string end_time = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearEndTime() {
        
        endTime_ = getDefaultInstance().getEndTime();
        onChanged();
        return this;
      }
      /**
       * <code>string end_time = 7;</code>
       * @param value The bytes for endTime to set.
       * @return This builder for chaining.
       */
      public Builder setEndTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        endTime_ = value;
        onChanged();
        return this;
      }

      private int status_ = 0;
      /**
       * <code>.conductor.proto.Workflow.WorkflowStatus status = 8;</code>
       * @return The enum numeric value on the wire for status.
       */
      @java.lang.Override public int getStatusValue() {
        return status_;
      }
      /**
       * <code>.conductor.proto.Workflow.WorkflowStatus status = 8;</code>
       * @param value The enum numeric value on the wire for status to set.
       * @return This builder for chaining.
       */
      public Builder setStatusValue(int value) {
        
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.conductor.proto.Workflow.WorkflowStatus status = 8;</code>
       * @return The status.
       */
      @java.lang.Override
      public com.netflix.conductor.proto.WorkflowPb.Workflow.WorkflowStatus getStatus() {
        @SuppressWarnings("deprecation")
        com.netflix.conductor.proto.WorkflowPb.Workflow.WorkflowStatus result = com.netflix.conductor.proto.WorkflowPb.Workflow.WorkflowStatus.valueOf(status_);
        return result == null ? com.netflix.conductor.proto.WorkflowPb.Workflow.WorkflowStatus.UNRECOGNIZED : result;
      }
      /**
       * <code>.conductor.proto.Workflow.WorkflowStatus status = 8;</code>
       * @param value The status to set.
       * @return This builder for chaining.
       */
      public Builder setStatus(com.netflix.conductor.proto.WorkflowPb.Workflow.WorkflowStatus value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        status_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.conductor.proto.Workflow.WorkflowStatus status = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatus() {
        
        status_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object input_ = "";
      /**
       * <code>string input = 9;</code>
       * @return The input.
       */
      public java.lang.String getInput() {
        java.lang.Object ref = input_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          input_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string input = 9;</code>
       * @return The bytes for input.
       */
      public com.google.protobuf.ByteString
          getInputBytes() {
        java.lang.Object ref = input_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          input_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string input = 9;</code>
       * @param value The input to set.
       * @return This builder for chaining.
       */
      public Builder setInput(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        input_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string input = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearInput() {
        
        input_ = getDefaultInstance().getInput();
        onChanged();
        return this;
      }
      /**
       * <code>string input = 9;</code>
       * @param value The bytes for input to set.
       * @return This builder for chaining.
       */
      public Builder setInputBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        input_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object output_ = "";
      /**
       * <code>string output = 10;</code>
       * @return The output.
       */
      public java.lang.String getOutput() {
        java.lang.Object ref = output_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          output_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string output = 10;</code>
       * @return The bytes for output.
       */
      public com.google.protobuf.ByteString
          getOutputBytes() {
        java.lang.Object ref = output_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          output_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string output = 10;</code>
       * @param value The output to set.
       * @return This builder for chaining.
       */
      public Builder setOutput(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        output_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string output = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearOutput() {
        
        output_ = getDefaultInstance().getOutput();
        onChanged();
        return this;
      }
      /**
       * <code>string output = 10;</code>
       * @param value The bytes for output to set.
       * @return This builder for chaining.
       */
      public Builder setOutputBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        output_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object reasonForIncompletion_ = "";
      /**
       * <code>string reason_for_incompletion = 11;</code>
       * @return The reasonForIncompletion.
       */
      public java.lang.String getReasonForIncompletion() {
        java.lang.Object ref = reasonForIncompletion_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          reasonForIncompletion_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string reason_for_incompletion = 11;</code>
       * @return The bytes for reasonForIncompletion.
       */
      public com.google.protobuf.ByteString
          getReasonForIncompletionBytes() {
        java.lang.Object ref = reasonForIncompletion_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          reasonForIncompletion_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string reason_for_incompletion = 11;</code>
       * @param value The reasonForIncompletion to set.
       * @return This builder for chaining.
       */
      public Builder setReasonForIncompletion(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        reasonForIncompletion_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string reason_for_incompletion = 11;</code>
       * @return This builder for chaining.
       */
      public Builder clearReasonForIncompletion() {
        
        reasonForIncompletion_ = getDefaultInstance().getReasonForIncompletion();
        onChanged();
        return this;
      }
      /**
       * <code>string reason_for_incompletion = 11;</code>
       * @param value The bytes for reasonForIncompletion to set.
       * @return This builder for chaining.
       */
      public Builder setReasonForIncompletionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        reasonForIncompletion_ = value;
        onChanged();
        return this;
      }

      private long executionTime_ ;
      /**
       * <code>int64 execution_time = 12;</code>
       * @return The executionTime.
       */
      @java.lang.Override
      public long getExecutionTime() {
        return executionTime_;
      }
      /**
       * <code>int64 execution_time = 12;</code>
       * @param value The executionTime to set.
       * @return This builder for chaining.
       */
      public Builder setExecutionTime(long value) {
        
        executionTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 execution_time = 12;</code>
       * @return This builder for chaining.
       */
      public Builder clearExecutionTime() {
        
        executionTime_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object event_ = "";
      /**
       * <code>string event = 13;</code>
       * @return The event.
       */
      public java.lang.String getEvent() {
        java.lang.Object ref = event_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          event_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string event = 13;</code>
       * @return The bytes for event.
       */
      public com.google.protobuf.ByteString
          getEventBytes() {
        java.lang.Object ref = event_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          event_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string event = 13;</code>
       * @param value The event to set.
       * @return This builder for chaining.
       */
      public Builder setEvent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        event_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string event = 13;</code>
       * @return This builder for chaining.
       */
      public Builder clearEvent() {
        
        event_ = getDefaultInstance().getEvent();
        onChanged();
        return this;
      }
      /**
       * <code>string event = 13;</code>
       * @param value The bytes for event to set.
       * @return This builder for chaining.
       */
      public Builder setEventBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        event_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object failedReferenceTaskNames_ = "";
      /**
       * <code>string failed_reference_task_names = 14;</code>
       * @return The failedReferenceTaskNames.
       */
      public java.lang.String getFailedReferenceTaskNames() {
        java.lang.Object ref = failedReferenceTaskNames_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          failedReferenceTaskNames_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string failed_reference_task_names = 14;</code>
       * @return The bytes for failedReferenceTaskNames.
       */
      public com.google.protobuf.ByteString
          getFailedReferenceTaskNamesBytes() {
        java.lang.Object ref = failedReferenceTaskNames_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          failedReferenceTaskNames_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string failed_reference_task_names = 14;</code>
       * @param value The failedReferenceTaskNames to set.
       * @return This builder for chaining.
       */
      public Builder setFailedReferenceTaskNames(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        failedReferenceTaskNames_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string failed_reference_task_names = 14;</code>
       * @return This builder for chaining.
       */
      public Builder clearFailedReferenceTaskNames() {
        
        failedReferenceTaskNames_ = getDefaultInstance().getFailedReferenceTaskNames();
        onChanged();
        return this;
      }
      /**
       * <code>string failed_reference_task_names = 14;</code>
       * @param value The bytes for failedReferenceTaskNames to set.
       * @return This builder for chaining.
       */
      public Builder setFailedReferenceTaskNamesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        failedReferenceTaskNames_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object externalInputPayloadStoragePath_ = "";
      /**
       * <code>string external_input_payload_storage_path = 15;</code>
       * @return The externalInputPayloadStoragePath.
       */
      public java.lang.String getExternalInputPayloadStoragePath() {
        java.lang.Object ref = externalInputPayloadStoragePath_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          externalInputPayloadStoragePath_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string external_input_payload_storage_path = 15;</code>
       * @return The bytes for externalInputPayloadStoragePath.
       */
      public com.google.protobuf.ByteString
          getExternalInputPayloadStoragePathBytes() {
        java.lang.Object ref = externalInputPayloadStoragePath_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          externalInputPayloadStoragePath_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string external_input_payload_storage_path = 15;</code>
       * @param value The externalInputPayloadStoragePath to set.
       * @return This builder for chaining.
       */
      public Builder setExternalInputPayloadStoragePath(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        externalInputPayloadStoragePath_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string external_input_payload_storage_path = 15;</code>
       * @return This builder for chaining.
       */
      public Builder clearExternalInputPayloadStoragePath() {
        
        externalInputPayloadStoragePath_ = getDefaultInstance().getExternalInputPayloadStoragePath();
        onChanged();
        return this;
      }
      /**
       * <code>string external_input_payload_storage_path = 15;</code>
       * @param value The bytes for externalInputPayloadStoragePath to set.
       * @return This builder for chaining.
       */
      public Builder setExternalInputPayloadStoragePathBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        externalInputPayloadStoragePath_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object externalOutputPayloadStoragePath_ = "";
      /**
       * <code>string external_output_payload_storage_path = 16;</code>
       * @return The externalOutputPayloadStoragePath.
       */
      public java.lang.String getExternalOutputPayloadStoragePath() {
        java.lang.Object ref = externalOutputPayloadStoragePath_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          externalOutputPayloadStoragePath_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string external_output_payload_storage_path = 16;</code>
       * @return The bytes for externalOutputPayloadStoragePath.
       */
      public com.google.protobuf.ByteString
          getExternalOutputPayloadStoragePathBytes() {
        java.lang.Object ref = externalOutputPayloadStoragePath_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          externalOutputPayloadStoragePath_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string external_output_payload_storage_path = 16;</code>
       * @param value The externalOutputPayloadStoragePath to set.
       * @return This builder for chaining.
       */
      public Builder setExternalOutputPayloadStoragePath(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        externalOutputPayloadStoragePath_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string external_output_payload_storage_path = 16;</code>
       * @return This builder for chaining.
       */
      public Builder clearExternalOutputPayloadStoragePath() {
        
        externalOutputPayloadStoragePath_ = getDefaultInstance().getExternalOutputPayloadStoragePath();
        onChanged();
        return this;
      }
      /**
       * <code>string external_output_payload_storage_path = 16;</code>
       * @param value The bytes for externalOutputPayloadStoragePath to set.
       * @return This builder for chaining.
       */
      public Builder setExternalOutputPayloadStoragePathBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        externalOutputPayloadStoragePath_ = value;
        onChanged();
        return this;
      }

      private int priority_ ;
      /**
       * <code>int32 priority = 17;</code>
       * @return The priority.
       */
      @java.lang.Override
      public int getPriority() {
        return priority_;
      }
      /**
       * <code>int32 priority = 17;</code>
       * @param value The priority to set.
       * @return This builder for chaining.
       */
      public Builder setPriority(int value) {
        
        priority_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 priority = 17;</code>
       * @return This builder for chaining.
       */
      public Builder clearPriority() {
        
        priority_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:conductor.proto.WorkflowSummary)
    }

    // @@protoc_insertion_point(class_scope:conductor.proto.WorkflowSummary)
    private static final com.netflix.conductor.proto.WorkflowSummaryPb.WorkflowSummary DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.netflix.conductor.proto.WorkflowSummaryPb.WorkflowSummary();
    }

    public static com.netflix.conductor.proto.WorkflowSummaryPb.WorkflowSummary getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<WorkflowSummary>
        PARSER = new com.google.protobuf.AbstractParser<WorkflowSummary>() {
      @java.lang.Override
      public WorkflowSummary parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new WorkflowSummary(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<WorkflowSummary> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<WorkflowSummary> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.netflix.conductor.proto.WorkflowSummaryPb.WorkflowSummary getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_conductor_proto_WorkflowSummary_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_conductor_proto_WorkflowSummary_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033model/workflowsummary.proto\022\017conductor" +
      ".proto\032\024model/workflow.proto\"\324\003\n\017Workflo" +
      "wSummary\022\025\n\rworkflow_type\030\001 \001(\t\022\017\n\007versi" +
      "on\030\002 \001(\005\022\023\n\013workflow_id\030\003 \001(\t\022\026\n\016correla" +
      "tion_id\030\004 \001(\t\022\022\n\nstart_time\030\005 \001(\t\022\023\n\013upd" +
      "ate_time\030\006 \001(\t\022\020\n\010end_time\030\007 \001(\t\0228\n\006stat" +
      "us\030\010 \001(\0162(.conductor.proto.Workflow.Work" +
      "flowStatus\022\r\n\005input\030\t \001(\t\022\016\n\006output\030\n \001(" +
      "\t\022\037\n\027reason_for_incompletion\030\013 \001(\t\022\026\n\016ex" +
      "ecution_time\030\014 \001(\003\022\r\n\005event\030\r \001(\t\022#\n\033fai" +
      "led_reference_task_names\030\016 \001(\t\022+\n#extern" +
      "al_input_payload_storage_path\030\017 \001(\t\022,\n$e" +
      "xternal_output_payload_storage_path\030\020 \001(" +
      "\t\022\020\n\010priority\030\021 \001(\005Bl\n\033com.netflix.condu" +
      "ctor.protoB\021WorkflowSummaryPbZ:github.co" +
      "m/netflix/conductor/client/gogrpc/conduc" +
      "tor/modelb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.netflix.conductor.proto.WorkflowPb.getDescriptor(),
        });
    internal_static_conductor_proto_WorkflowSummary_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_conductor_proto_WorkflowSummary_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_conductor_proto_WorkflowSummary_descriptor,
        new java.lang.String[] { "WorkflowType", "Version", "WorkflowId", "CorrelationId", "StartTime", "UpdateTime", "EndTime", "Status", "Input", "Output", "ReasonForIncompletion", "ExecutionTime", "Event", "FailedReferenceTaskNames", "ExternalInputPayloadStoragePath", "ExternalOutputPayloadStoragePath", "Priority", });
    com.netflix.conductor.proto.WorkflowPb.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
